### ISSUE TITLE
Typescript?

### ISSUE THREAD

**Issue by RoVixen** [realcoloride/node_characterai#102]
Are you planning on add types to the code? I could help you with that if you like

**Comment by RoVixen** [comment]
At least to have the intelisense it could be done with comments
https://www.typescriptlang.org/docs/handbook/intro-to-js-ts.html

**Comment by Parking-Master** [comment]
See #69

**Comment by RoVixen** [comment]
but that doesnt fully solves the typing and they can be added from before without doing anything like taking them out of node_modules

**Comment by Parking-Master** [comment]
You'll have to wait until @realcoloride responds then

**Comment by realcoloride** [comment]
Will consider this. #100 might be linked aswell

**Comment by Parking-Master** [comment]
@realcoloride yep, it's a pretty high requested thing. You might consider adding that in the future. I won't be able to help you though because I don't know Typescript either

**Comment by realcoloride** [comment]
Hey there, sorry for the long wait. Check the issue
