### ISSUE TITLE
Error: Already authenticated

### ISSUE THREAD

**Issue by iKat20** [realcoloride/node_characterai#107]
I've been trying to use the package on a project that I have, however, I still get the "Already authenticated" error.
Here is my code snippet.
```
const CharacterAI = require("node_characterai")
const characterAI = new CharacterAI()
const pogger = require("pogger")
const config = require("../../config.json")
module.exports = async (message, client) => {
    await characterAI.authenticateWithToken(process.env.CHARACTERAI_TOKEN)

    if (!message.channel.id === config.characters.jax.channel) return message.reply("You can't do this in this channel")
    if (!characterAI.isAuthenticated()) pogger.error("Can't process your request. Unauthenticated.")
    const chat = await characterAI.createOrContinueChat(config.characters.jax.id) 
    const res = await chat.sendAndAwaitResponse(message.content, true)
    message.reply(res.text)
        
  };
```

**Comment by realcoloride** [comment]
"Already authenticated" happens when you call authenticateWithToken() twice without using unauthenticate().
**Make sure you are calling authenticateWithToken() once.**

**Comment by iKat20** [comment]
So, if I understand properly, I can initiate it in my `index.js` once, and that is it?

**Comment by realcoloride** [comment]
Should be. I don't have your full code but yes. Initialize your client and chat once (or only when needed) and use chat.sendAndAwaitResponse anytime to send a message to your ai.

You need to think of it as if you were on the website.

**Comment by Parking-Master** [comment]
You are exporting thr module as one function, to send a message. Instead of sending the message first, it authenticates first, multiple times when using the function. Move that authenticateWithToken function outside of your module.exports scripts so it only authenticates once.

**Comment by iKat20** [comment]
Update :: I did put my Token Authentication in my index file, but, somehow, it doesnt authenticate anymore. Could it be my token who's expired?

**Comment by realcoloride** [comment]
Hello, do you still have issues?

**Comment by iKat20** [comment]
Affirm! Tried to export it, but didn't figured out yet

Exported it as functions, init in "index", but stays as Already Authenticated/Unauthenticated

**Comment by realcoloride** [comment]
Could you send your code again please?

**Comment by iKat20** [comment]
Deleted it and started from scratch, didn't went back on it yet

**Comment by realcoloride** [comment]
Ok, make sure you dont authenticate more than once. Happy coding!
