### ISSUE TITLE
fetch is not defined

### ISSUE THREAD

**Issue by JcynR** [realcoloride/node_characterai#11]
I tried installing node-fetch manually but it didn't fix it.

```
client.js:193
const request = await fetch('https://beta.character.ai/chat/auth/lazy/', {
                ^
ReferenceError: fetch is not defined
```

**Comment by realcoloride** [comment]
Hello
do `npm install node-fetch`

**Comment by JcynR** [comment]
I did that.

**Comment by JcynR** [comment]
Looks like you didn't import the package in client.js

**Comment by realcoloride** [comment]
I don't have to, it works without having to require anything

Though you might wanna install cross fetch, in what environment and node version do you run?

**Comment by JcynR** [comment]
Okay, I see what's happening,I'm running v16.6.2 but in version 18.0.0 they apparently added fetch to the global scope

Check it:
https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V18.md#fetch-experimental

I may have to upgrade then... but I can't at this time. Maybe you should make that clear or make it compatible with older versions.

**Comment by realcoloride** [comment]
Hello

How should I? And thanks for confirming that it's because of node's version

**Comment by JcynR** [comment]
I upgraded to v18 so for me it's not a problem anymore. But if you want to make it compatible with older versions, you could just use the node-fetch library instead. All you have to do is import it.
