### ISSUE TITLE
.puppeteerPath not working correctly. 

### ISSUE THREAD

**Issue by Eizen724** [realcoloride/node_characterai#112]
Hello guys. It's my first time submiting an issue and also english is not rly good so feel free to ask if you don't understand smth. 

So i'm actually trying to use node_charachter ai on a debian 10 vps with a docker container node:18-alpine and in my container i have the chromium-browser at "/usr/bin/chromium-browser" but when i launch my app it show me an error. And i setup .puppeteerPath for locate chromium-browser correctly but the error is still occuring. 

![2023-11-10_23h30_44](https://github.com/realcoloride/node_characterai/assets/114910540/234d8d41-1588-4dc9-a373-bcec1a6abb61)
![2023-11-10_23h31_47](https://github.com/realcoloride/node_characterai/assets/114910540/5b5e4513-3587-4dda-af65-dd4ff419b258)

**Comment by realcoloride** [comment]
See https://github.com/realcoloride/node_characterai/issues/110#issuecomment-1799248756

**Comment by Eizen724** [comment]
Tanks for the quick answer but i have already check this issue before posting mine. And i know that my chromium-browser is at "/usr/bin/chromium-browser" 

![2023-11-11_11h22_59](https://github.com/realcoloride/node_characterai/assets/114910540/03eb42bc-bed0-4e77-b9b0-5bcc9a18a766)

So i do more test and i discover smth weird. 
When i use characterAI.puppeteerPath my client look like this : 

![2023-11-11_11h28_06](https://github.com/realcoloride/node_characterai/assets/114910540/248fa781-0845-4a80-a471-d7c21831b556)

I don't know if it's normal but the issue keep occuring. So I edit the my code for : 
characterAI.requester.puppeteerPath = "/usr/bin/chromium-browser";

and after that i don't get the the error about pptr  but i still don't get any response from characterai. I got this new error when i stop my container : 

![image](https://github.com/realcoloride/node_characterai/assets/114910540/050bb5fc-58a0-4dbe-a954-fc24b25d263f)

but this error is maybe here because i stop my container so it's stop the browser too.

**Comment by Parking-Master** [comment]
ENOENT means no file or directory exists in the path. The referring path is `/root/.cache/puppeteer/chrome/linux-1108766/chrome-linux/chrome`.

This is the cache directory for chromium, whereas the browser is unable to launch without it.

So, what the problem seems to be is that chromium _was_ installed, but something broke it after/during the installation.

https://stackoverflow.com/questions/59979188/error-failed-to-launch-the-browser-process-puppeteer

Also, could you try running this and paste the output?
```
ls /root/.cache/puppeteer/chrome/linux-1108766/
```

**Comment by Eizen724** [comment]
Yes of course. 
This is the output : 
![2023-11-17_10h13_44](https://github.com/realcoloride/node_characterai/assets/114910540/56afff06-ad3d-4798-a0b8-0218744c6af1)

You are right the file have the wrong name. I don't actually have the time to try but I'll give you an update later.

**Comment by Eizen724** [comment]
Ah no my bad i was thinking the installation was wrong but it look fine

**Comment by Eizen724** [comment]
Also here is how i install chrome in my dockerfile : 
`
RUN apk add --no-cache \
      chromium \
      nss \
      freetype \
      harfbuzz \
      ca-certificates \
      ttf-freefont \
      nodejs 
`

**Comment by Parking-Master** [comment]
Thanks. Could you also run this?

```
ls /root/.cache/puppeteer/chrome/linux-1108766/chrome-linux
```

**Comment by realcoloride** [comment]
No response from OP, closing issue. Please re-open this issue if you need to update, or elaborate on your problem.
Cheers
