### ISSUE TITLE
Recreate new Chat

### ISSUE THREAD

**Issue by StrongCatto** [realcoloride/node_characterai#113]
Hi! 
node_characterai works perfect and doing very great!
although I have 1 request (idk if this ever being discussed or not)
but is there any way for us to create a new chat (new session)?
as currently I need to login into browser and delete it manually.

Thank you!

**Comment by realcoloride** [comment]
See `chat.js`, the current methods are:
changeToConversationId() -> changes to another conversation
getSavedConversations() -> fetches all the other conversations
saveAndStartNewChat() -> creates a new conversation and swaps to the new conversation

Aswell, when doing createOrContinueChat(), you can choose a specific conversation id (externalId) to directly create the chat object from the client.

So yes, you can create a new chat.

Thanks for your support & happy coding!
