### ISSUE TITLE
`characterAI.requester.usePlus = true;`  not working

### ISSUE THREAD

**Issue by ftk789** [realcoloride/node_characterai#114]
So I bought plus and re-logged in, and I re-copied the access-token, But now when I request, It does nothing, It just keeps hanging, No reply at all, Any fix for this?

**Comment by ftk789** [comment]
I also made sure to debug if it's actually on the plus.character.ai site, And yet still doesn't work.

**Comment by Parking-Master** [comment]
Are you sure this is only for plus users? This seems like a common issue with the package even with regular users.

**Comment by ftk789** [comment]
> Are you sure this is only for plus users? This seems like a common issue with the package even with regular users.

Yes I am sure, When I'm on an account that never subbed, It instantly works and pretty quick as well, But when I login through my subbed account, It just doesn't respond, It logs out the " Done setup " But it just doesn't do anything after that, So yes I am pretty sure, Right now I'm using it on my alt non-subbed account and it works fine.

**Comment by ftk789** [comment]
I have debugged if it works as in it loads plus.character.ai instead of beta.xxx..... , And it works it does log the plus site, But yet it still does not work.

**Comment by Parking-Master** [comment]
Ok, thanks for the info. Definitely strange. @realcoloride could you check this out?

**Comment by realcoloride** [comment]
Set the headless mode to false and see what pops on the browser screen. See the page you get when its frozen and see what appears in the console aswell.
I cannot reproduce the issue since I don't own CAI+.

Keep me updated.

**Comment by ftk789** [comment]
> Set the headless mode to false and see what pops on the browser screen. See the page you get when its frozen and see what appears in the console aswell. I cannot reproduce the issue since I don't own CAI+.
> 
> Keep me updated.

Okay I will be doing that and testing it out and letting you know what could be the issue.

**Comment by ftk789** [comment]
After some investigation without headless mode as you said, Apperantly, this comes up:

![image](https://github.com/realcoloride/node_characterai/assets/57598907/ad020c3f-72d3-4acc-b987-8d1521d933e5)


Can't show the body cuz it contains the key, But basically it opens `plus.character.ai` , But then it returns me to `beta.character.ai/dj-rest-auth/auth0/` 

And I think this is why it doesn't load anything in any case, Cuz as soon as you sub, It saves a cookie on your PC that keeps directing you to `plus.character.ai` if you subbed once, So this could be the issue as well

**Comment by ftk789** [comment]
The main issue here is that, When you have plus once, You'll always have it, Meaning even if your sub exprired, You'll be directed to `plus.charater.ai` which then presents the "purchase " popout:

Here's an example when I logout frmo a subbed account:

![image](https://github.com/realcoloride/node_characterai/assets/57598907/37204f36-ca7c-4175-a962-fb2e1bc15b07)

The cookie now is fully saved as you're a plus user and need to pay again, You can easily fix this with clearing the data of the site on Chrome, But this could be the issue.

**Comment by Parking-Master** [comment]
@ftk789 nice job fixing it!

**Comment by ftk789** [comment]
> @ftk789 nice job fixing it!

Thank you man, Now You guys need to update this no?

**Comment by Parking-Master** [comment]
@ftk789 sure! Could you paste the file you changed on here and I'll open a PR?

**Comment by ftk789** [comment]
> @ftk789 sure! Could you paste the file you changed on here and I'll open a PR?

I had to change 3 files here they are:
client.js :
`const Chat = require("./chat");
const uuidv4 = require("uuid").v4;
const Parser = require("./parser");
const Requester = require("./requester");

class Client {
    #token = undefined;
    #isGuest = false;
    #authenticated = false;
    usePlus = false;
    #guestHeaders = {
        "content-type": "application/json",
        "user-agent": "CharacterAI/1.0.0 (iPhone; iOS 14.4.2; Scale/3." + Math.random().toFixed(1).split(".")[1] + ")"
    }
    requester = new Requester();

    constructor() {
        this.#token = undefined;
    }

    // api fetching
    async fetchCategories() {
        const request = await this.requester.request("https://" + (this.usePlus ? "plus" : "beta") + ".character.ai/chat/character/categories/");

        if (request.status() === 200) return await Parser.parseJSON(request);
        else throw Error("Failed to fetch categories");
    }
    async fetchUserConfig() {
        const request = await this.requester.request("https://" + (this.usePlus ? "plus" : "beta") + ".character.aichat/config/", {
            headers: this.#guestHeaders
        });

        if (request.status() === 200) {
            const response = await Parser.parseJSON(request);

            return response;
        } else Error("Failed fetching user configuration.");
    }
    async fetchUser() {
        if (!this.isAuthenticated()) throw Error("You must be authenticated to do this.");

        const request = await this.requester.request("https://" + (this.usePlus ? "plus" : "beta") + ".character.ai/chat/user/", {
            headers: this.getHeaders()
        });

        if (request.status() === 200) {
            const response = await Parser.parseJSON(request);

            return response;
        } else Error("Failed fetching user.");
    }
    async fetchFeaturedCharacters() {
        if (!this.isAuthenticated()) throw Error("You must be authenticated to do this.");

        const request = await this.requester.request("https://" + (this.usePlus ? "plus" : "beta") + ".character.ai/chat/characters/featured_v2/", {
            headers: this.getHeaders()
        });

        if (request.status() === 200) {
            const response = await Parser.parseJSON(request);

            return response;
        } else Error("Failed fetching featured characters.");
    }
    async fetchCharactersByCategory(curated = false) {
        if (curated == undefined || typeof(curated) != "boolean") throw Error("Invalid arguments.");

        const url = `https://" + ${this.usePlus ? "plus" : "beta"} + ".character.ai/chat/${
            curated ? "curated_categories" : "categories"
        }/characters/`;

        const request = await this.requester.request(url, {
            headers: this.#guestHeaders
        });

        const property = curated ? "characters_by_curated_category" : "characters_by_category";

        if (request.status() === 200) {
            const response = await Parser.parseJSON(request);

            return response[property]
        } else Error("Failed fetching characters by category.");
    }
    async fetchCharacterInfo(characterId) {
        if (!this.isAuthenticated()) throw Error("You must be authenticated to do this.");
        if (characterId == undefined || typeof(characterId) != "string") throw Error("Invalid arguments.");
        
        const request = await this.requester.request(`https://" + ${this.usePlus ? "plus" : "beta"} + ".character.ai/chat/character/info/`, {
            headers: this.getHeaders(),
            body: Parser.stringify({
                external_id: characterId
            }),
            method: "POST"
        });
        
        console.log(request);

        if (request.status() === 200) {
            const response = await Parser.parseJSON(request);

            return response.character;
        } else Error("Could not fetch character information.");
    }
    async searchCharacters(characterName) {
        if (!this.isAuthenticated()) throw Error("You must be authenticated to do this.");
        if (this.#isGuest) throw Error("Guest accounts cannot use the search feature.");
        if (characterName == undefined || typeof(characterName) != "string") throw Error("Invalid arguments.");

        const request = await this.requester.request(`https://" + ${this.usePlus ? "plus" : "beta"} + ".character.ai/chat/characters/search/?query=${characterName}`, {
            headers: this.getHeaders()
        });

        if (request.status() === 200) {
            const response = await Parser.parseJSON(request);

            return response;
        } else Error("Could not search for characters.");
    }
    async getRecentConversations() {
        if (!this.isAuthenticated()) throw Error("You must be authenticated to do this.");
        const request = await this.requester.request(`https://" + ${this.usePlus ? "plus" : "beta"} + ".character.ai/chat/characters/recent/`, {
            headers: this.getHeaders()
        });

        if (request.status() === 200) {
            const response = await Parser.parseJSON(request);

            return response;
        } else Error("Could not get recent conversations.");
    }

    // chat
    async createOrContinueChat(characterId, externalId = null) {
        if (!this.isAuthenticated()) throw Error("You must be authenticated to do this.");
        if (characterId == undefined || typeof(characterId) != "string" || typeof(externalId != null ? externalId : "") != "string") throw Error("Invalid arguments.");

        let request = await this.requester.request("https://" + (this.usePlus ? "plus" : "beta") + ".character.ai/chat/history/continue/",    {
            body: Parser.stringify({
                character_external_id: characterId,
                history_external_id: externalId,
            }),
            method: "POST",
            headers: this.getHeaders()
        });

        if (request.status() === 200 || request.status() === 404) {
            let response = await request.text();

            if (response === "No Such History" || response === "there is no history between user and character") { // Create a new chat
                request = await this.requester.request("https://" + (this.usePlus ? "plus" : "beta") + ".character.ai/chat/history/create/", {
                    body: Parser.stringify({
                        character_external_id: characterId,
                        history_external_id: null,
                    }),
                    method: "POST",
                    headers: this.getHeaders()
                });
                if (request.status() === 200) response = await Parser.parseJSON(request);
                else Error("Could not create a new chat.");
            }

            // If a text gets returned, we try to parse it to JSON!
            try {
                response = JSON.parse(response);
            } catch (error) {}

            // Continue it
            const continueBody = response;
            return new Chat(this, characterId, continueBody);
        } else Error("Could not create or resume a chat.");
    }

    // Fetch speech from text using provided voice id
    async fetchTTS(voiceId, toSpeak) {
        if (!this.isAuthenticated()) throw Error("You must be authenticated to do this.");
        if (!voiceId || !toSpeak || typeof(voiceId) != "number" || typeof(toSpeak) != "string") throw Error("Invalid arguments.");

        let request = await this.requester.request(`https://" + ${this.usePlus ? "plus" : "beta"} + ".character.ai/chat/character/preview-voice/?voice_id=${voiceId}&to_speak=${toSpeak}`, {
            headers: this.getHeaders()
        });

        if (request.status() === 200) {
            const response = await Parser.parseJSON(request);
            
            return response.speech;
        } else Error("Could not fetch speech");
    }

    // Fetch character voices
    async fetchTTSVoices() {
        if (!this.isAuthenticated()) throw Error("You must be authenticated to do this.");

        let request = await this.requester.request("https://" + (this.usePlus ? "plus" : "beta") + ".character.ai/chat/character/voices/", {
            headers: this.getHeaders()
        });

        if (request.status() === 200) {
            const response = await Parser.parseJSON(request);
            
            return response.voices;
        } else Error("Could not fetch voices");
    }

    // authentification
    async authenticateWithToken(token) {
        if (this.isAuthenticated()) throw Error("Already authenticated");
        if (!token || typeof(token) != "string") throw Error("Specify a valid token");

        await this.requester.initialize();

        const request = await this.requester.request("https://" + (this.usePlus ? "plus" : "beta") + ".character.ai/dj-rest-auth/auth0/", {
            method: "POST",
            body: Parser.stringify({
                access_token: token
            }),
            headers: {
                "Content-Type": "application/json",
            }
        });
        if (request.status() === 200) {
            const response = await Parser.parseJSON(request);

            this.#isGuest = false;
            this.#authenticated = true;
            this.#token = response.key;

            return response.token
        } else throw Error("Authentication token is invalid");
    }
    async authenticateAsGuest() {
        if (this.isAuthenticated()) throw Error("Already authenticated");
        console.log("[node_characterai] Puppeteer - Warning: Guest users can only send up to 10 messages.");
        await this.requester.initialize();

        let generating = false;
        let request;

        let uuid = uuidv4();

        // This is experimental but forces authentication
        for (let i = 0; i < 20; i++) {
            generating = true;

            uuid = uuidv4();
            const payload = JSON.stringify({
                lazy_uuid: uuid,
            });

            const baseRequest = await Promise.race([
                this.requester.request("https://" + (this.usePlus ? "plus" : "beta") + ".character.ai/chat/auth/lazy/", {
                    method: "POST",
                    body: payload,
                    headers: this.#guestHeaders,
                }),
                new Promise(resolve => setTimeout(() => resolve(null), 2000))
            ]);

            request = baseRequest;
            generating = false;

            if (request) break;
        }

        if (request.status() === 200) {
            const response = await Parser.parseJSON(request);

            if (response.success === true) {
                this.#isGuest = true;
                this.#authenticated = true;
                this.#token = response.token;
                this.uuid = uuid;

                return response.token;
            } else throw Error("Registering failed");
        } else throw Error("Failed to fetch a lazy token");
    }
    unauthenticate() {
        if (this.isAuthenticated()) {
            this.#authenticated = false;
            this.#isGuest = false;
            this.#token = undefined;
            this.requester.uninitialize();
        }
    }

    // getters
    getToken() {
        return this.#token;
    }
    isGuest() {
        return this.#isGuest;
    }
    isAuthenticated() {
        return (this.#authenticated);
    }

    // headers
    getHeaders() {
        return {
            authorization: `Token ${this.#token}`,
            "Content-Type": "application/json",
            // "user-agent": "CharacterAI/1.0.0 (iPhone; iOS 14.4.2; Scale/3.00)",
            // "sec-ch-ua": `"Not_A Brand";v="99", "Google Chrome";v="109", "Chromium";v="109"`,
            // "sec-ch-ua-mobile": "?0",
            // "sec-ch-ua-platform": "Windows",
            // "sec-fetch-dest": "empty",
            // "sec-fetch-mode": "cors",
            // "sec-fetch-site": "same-origin"
        };
    }
};

module.exports = Client;
`
chat.js : 
`const { Reply, Message, MessageHistory, OutgoingMessage } = require("./message");
const Parser = require("./parser");
const jimp = require("jimp");
const mime = require("mime");

class Chat {
    constructor(client, characterId, continueBody) {
        this.characterId = characterId;
        this.externalId = continueBody.external_id;

        this.client = client;
        usePlus = false;

        const ai = continueBody.participants.find((participant) => participant.is_human === false);
        this.aiId = ai.user.username;
        this.requester = client.requester;
    }

    async fetchHistory(pageNumber) {
        if (!this.client.isAuthenticated()) throw Error("You must be authenticated to do this.");

        // Page number is optional
        if (pageNumber) {
            if (typeof(pageNumber) != "number") throw Error("Invalid arguments");
        }

        const client = this.client;

        const pageString = pageNumber ? `&page_num=${pageNumber}` : ""

        const request = await this.requester.request(`https://" + ${this.usePlus ? "plus" : "beta"} + ".character.ai/chat/history/msgs/user/?history_external_id=${this.externalId}${pageString}`, {
            headers:client.getHeaders()
        })

        if (request.status() === 200) {
            const response = await Parser.parseJSON(request)
            const historyMessages = response.messages;
            const messages = [];

            for (let i = 0; i < historyMessages.length; i++) {
                const message = historyMessages[i];

                messages.push(new Message(this, message));
            }

            const hasMore = response.has_more;
            const nextPage = response.next_page;
            return new MessageHistory(this, messages, hasMore, nextPage);
        } else Error("Could not fetch the chat history.")
    }
    async sendAndAwaitResponse(optionsOrMessage, singleReply) {
        if (!this.client.isAuthenticated()) throw Error("You must be authenticated to do this.");

        const payload = new OutgoingMessage(this, optionsOrMessage)
        const client = this.client;

        if (!client.isAuthenticated()) throw Error("You must be authenticated to do this.");

        const request = await this.requester.request("https://" + (this.usePlus ? "plus" : "beta") + ".character.ai/chat/streaming/", {
            body:Parser.stringify(payload),
            method:"POST",
            headers:client.getHeaders(),
            client:this.client
        }, true)

        if (request.status() === 200) {
            const response = await Parser.parseJSON(request);
            const replies = response.replies;

            const messages = []

            for (let i = 0; i < replies.length; i++) {
                messages.push(new Reply(this, response));
            }
            
            if (!singleReply) return messages;
            else return messages.pop();
        } else throw Error("Failed sending message.")
    }
    
    // Image generation
    async uploadImage(content, mimeType = null) {
        if (!this.client.isAuthenticated()) throw Error("You must be authenticated to do this.");
        
        /*
            Content Types:

            * Image URL
            * File Path
            * Buffer
            * ReadableStream
        */
        
        let buffer;

        try {
            // Auto detection for mime type
            if (!mimeType) {
                try {
                    url = new URL(content).pathname;
                    contentType = mime.getType(url);
                } catch (error) {}
                if (fs.existsSync(content)) mimeType = mime.getType(content);
            }
            
            const image = await jimp.read(content);
            buffer = image.getBase64(mimeType || "image/png");
        } catch (error) {
            throw Error("Content is invalid or not an image");
        }
        if (!buffer) throw Error("Invalid content");

        const client = this.client;

        const error = () => {
            throw Error("Failed uploading image.");
        };
        try {
            const request = this.requester.uploadBuffer(buffer, client);
            
            if (request.status() === 200) {
                return `https://characterai.io/i/400/static/user/${request.response}`;
            } else error();
        } catch (error) {
          error();
        }
    }
    async generateImage(prompt) {
        if (!this.client.isAuthenticated()) throw Error("You must be authenticated to do this.");
        
        const client = this.client;

        if (!client.isAuthenticated()) throw Error("You must be authenticated to do this.");
        if (typeof prompt != "string") throw Error("Invalid arguments");

        const request = await this.requester.request("https://" + (this.usePlus ? "plus" : "beta") + ".character.ai/chat/generate-image/", {
            headers: client.getHeaders(),
            method: "POST",
            client: this.client,
            body: Parser.stringify({
              image_description: prompt
            })
        }, true);

        if (request.status() === 200) {
            const response = await Parser.parseJSON(request);
            return response.image_rel_path;
        } else throw Error("Failed generating image.")
    }

    // Conversations
    async changeToConversationId(conversationExternalId, force = false) {
        if (typeof(conversationExternalId) != "string" || typeof(force) != "boolean") throw Error("Invalid arguments");
        if (!this.client.isAuthenticated()) throw Error("You must be authenticated to do this.");

        // Force means that we dont check if the conversation exists, may lead to errors
        let passing = false;

        if (!force) {
            let conversations = await this.getSavedConversations();
            conversations = conversations.histories;

            for (let i = 0; i < conversations.length; i++) {
                const conversation = conversations[i];
                if (conversation.external_id == conversationExternalId) passing = true;
            }
        } else passing = true;
        
        if (passing) this.externalId = conversationExternalId;
        else Error("Could not switch to conversation, it either doesn't exist or is invalid.")
    }
    async getSavedConversations(amount = 50) {
        if (typeof(amount) != "number") throw Error("Invalid arguments");
        if (!this.client.isAuthenticated()) throw Error("You must be authenticated to do this.");

        const client = this.client;
        const request = await this.requester.request(`https://" + ${this.usePlus ? "plus" : "beta"} + ".character.ai/chat/character/histories/`, {
            headers:client.getHeaders(),
            method:"POST",
            body: Parser.stringify({
                "external_id" : this.characterId,
                "number" : amount
            })
        })

        if (request.status() === 200) {
            const response = await Parser.parseJSON(request)
            
            this.externalId = response.external_id;
            return response;
        } else throw Error("Failed saving & creating new chat.")
    }

    // Messages
    async getMessageById(messageId) {
        //if (typeof(messageId) != "string") throw Error("Invalid arguments - (Message ids are now strings)");
        messageId = messageId.toString();
        if (!this.client.isAuthenticated()) throw Error("You must be authenticated to do this.");

        const history = await this.fetchHistory()
        const historyMessages = history.messages;

        for (let i = 0; i < historyMessages.length; i++) {
            const message = historyMessages[i];
            
            if (message.id == messageId) return message;
        }
        return null;
    }
    async deleteMessage(messageId) {
        if (typeof(messageId) != "string") throw Error("Invalid arguments - (Message ids are now strings)");
        if (!this.client.isAuthenticated()) throw Error("You must be authenticated to do this.");
        if (this.client.isGuest()) throw Error("Guest accounts cannot delete messsages.");

        const client = this.client;
        const request = await this.requester.request(`https://" + ${this.usePlus ? "plus" : "beta"} + ".character.ai/chat/history/msgs/delete/`, {
            headers:client.getHeaders(),
            method:"POST",
            body: Parser.stringify({
                "history_id" : this.externalId,
                "ids_to_delete" : [messageId],
                "regenerating" : false
            })
        })

        let passing = false;

        if (request.status() === 200) {
            const response = await Parser.parseJSON(request);
            
            if (response.status === "OK") passing = true;
        }

        if (!passing) throw Error("Failed to delete the message.");
    }
    async deleteMessages(messageIds) {
        if (!this.client.isAuthenticated()) throw Error("You must be authenticated to do this.");
        if (this.client.isGuest()) throw Error("Guest accounts cannot delete messsages.");

        const messagesToDelete = [];

        try {
            for (let i = 0; i < messageIds.length; i++) {
                const messageId = messageIds[i];

                if (typeof(messageId) == "string") {
                    messagesToDelete.push(messageId);
                }
            }
        } catch (error) {
            throw Error("Failed to delete messages.")
        };

        const client = this.client;
        const request = await this.requester.request(`https://" + ${this.usePlus ? "plus" : "beta"} + ".character.ai/chat/history/msgs/delete/`, {
            headers:client.getHeaders(),
            method:"POST",
            body: Parser.stringify({
                "history_id" : this.externalId,
                "ids_to_delete" : messagesToDelete,
                "regenerating" : false
            })
        })

        let passing = false;

        if (request.status() === 200) {
            const response = await Parser.parseJSON(request);
            
            if (response.status === "OK") passing = true;
        }

        if (!passing) throw Error("Failed to delete messages.");
    }
    async deleteMessagesBulk(amount = 50, descending = false) {
        if (typeof(amount) != "number") throw Error("Invalid arguments");
        if (!this.client.isAuthenticated()) throw Error("You must be authenticated to do this.");
        if (this.client.isGuest()) throw Error("Guest accounts cannot bulk delete messsages.");

        let idsToDelete = [];

        const history = await this.fetchHistory()
        const historyMessages = history.messages;

        for (let i = 0; i < amount; i++) {
            if (!descending) i = (amount - i);
            const message = historyMessages[i];
            
            if (message) idsToDelete.push(message.id);
        }

        if (idsToDelete.length == 0) return;

        const client = this.client;
        const request = await this.requester.request(`https://" + ${this.usePlus ? "plus" : "beta"} + ".character.ai/chat/history/msgs/delete/`, {
            headers:client.getHeaders(),
            method:"POST",
            body: Parser.stringify({
                "history_id" : this.externalId,
                "ids_to_delete" : idsToDelete,
                "regenerating" : false
            })
        })
        let passing = false;

        if (request.status() === 200) {
            const response = await Parser.parseJSON(request);

            if (response.status === "OK") passing = true;
        }

        if (!passing) throw Error("Failed to bulk delete messages.");
    }

    async saveAndStartNewChat() {
        if (!this.client.isAuthenticated()) throw Error("You must be authenticated to do this.");

        const client = this.client;
        const request = await this.requester.request(`https://" + ${this.usePlus ? "plus" : "beta"} + ".character.ai/chat/history/create/`, {
            headers:client.getHeaders(),
            method:"POST",
            body: Parser.stringify({
                "character_external_id" : this.characterId
            })
        })

        if (request.status() === 200) {
            const response = await Parser.parseJSON(request)
            
            this.externalId = response.external_id;
            return response;
        } else throw Error("Failed saving & creating new chat.")
    }
}

module.exports = Chat;
`

requester.js : 

`const puppeteer = require("puppeteer-extra");
const StealthPlugin = require("puppeteer-extra-plugin-stealth")
const fs = require("fs");

let chromiumPath = process.platform === "linux" ? "/usr/bin/chromium-browser" : null;
if (chromiumPath && !fs.existsSync(chromiumPath)) console.log("[node_characterai] Puppeteer - Warning: the specified Chromium path for puppeteer could not be located. If the script does not work properly, you may need to specify a path to the Chromium binary file/executable.");

class Requester {
    browser = undefined;
    page = undefined;

    #initialized = false;
    #hasDisplayed = false;

    #headless = "new";
    puppeteerPath = undefined;
    puppeteerLaunchArgs = [
        "--fast-start",
        "--disable-extensions",
        "--no-sandbox",
        "--disable-setuid-sandbox",
        "--no-gpu",
        "--disable-background-timer-throttling",
        "--disable-renderer-backgrounding",
        "--override-plugin-power-saver-for-testing=never",
        "--disable-extensions-http-throttling",
        "--user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.3"
    ];
    puppeteerNoDefaultTimeout = false;
    puppeteerProtocolTimeout = 0;
    usePlus = false;
    forceWaitingRoom = false;

    constructor() {}
    isInitialized() {
        return this.#initialized;
    }
    async waitForWaitingRoom(page) {
        // Enable force waiting room to ensure you check for waiting room even on C.AI+
        if (!this.usePlus || (this.usePlus && this.forceWaitingRoom)) {
            return new Promise(async (resolve) => {
                try {
                    let interval;
                    let pass = true;

                    const minute = 60000; // Update every minute

                    // Keep waiting until false
                    async function check() {
                        if (pass) {
                            pass = false;

                            const waitingRoomTimeLeft = await page.evaluate(async() => {
                                try {
                                    const contentContainer = document.querySelector(".content-container");
                                    const sections = contentContainer.querySelectorAll("section");
                                    const h2Element = sections[1].querySelector("h2");
                                    const h2Text = h2Element.innerText;
                                    const regex = /\d+/g;
                                    const matches = h2Text.match(regex);

                                    if (matches) return matches[0];
                                } catch (error) {
                                    return;
                                }
                            }, minute);

                            const waiting = (waitingRoomTimeLeft != null);
                            if (waiting) {
                                console.log(`[node_characterai] Puppeteer - Currently in cloudflare's waiting room. Time left: ${waitingRoomTimeLeft}`);
                            } else {
                                resolve();
                                clearInterval(interval);
                            }
                            pass = true;
                        };
                    }

                    interval = setInterval(check, minute);
                    await check();
                } catch (error) {
                    console.log("[node_characterai] Puppeteer - There was a fatal error while checking for cloudflare's waiting room");
                    console.log(error);
                }
            });
        }
    }
    async initialize() {
        if (!this.isInitialized());

        // Handle chromium tabs cleanup
        process.on('exit', () => {
            this.uninitialize();
        });

        console.log("[node_characterai] Puppeteer - This is an experimental feature. Please report any issues on github.");

        puppeteer.use(StealthPlugin())
        const browser = await puppeteer.launch({
            headless: this.#headless,
            args: this.puppeteerLaunchArgs,
            protocolTimeout: this.puppeteerProtocolTimeout || 0, // Props to monckey100
            executablePath: this.puppeteerPath || null
        });
        this.browser = browser;

        let page = await browser.pages();
        page = page[0];
        this.page = page;

        await page.setRequestInterception(false);

        page.setViewport({
            width: 1920 + Math.floor(Math.random() * 100),
            height: 3000 + Math.floor(Math.random() * 100),
            deviceScaleFactor: 1,
            hasTouch: false,
            isLandscape: false,
            isMobile: false,
        });
        await page.setJavaScriptEnabled(true);
        await page.setDefaultNavigationTimeout(0);

        const userAgent = "CharacterAI/1.0.0 (iPhone; iOS 14.4.2; Scale/3.00)";
        await page.setUserAgent(userAgent);

        // Special thanks to @Parking-Master for this fix
        await page.deleteCookie();
        const client = await page.target().createCDPSession();
        await client.send("Network.clearBrowserCookies");
        await client.send("Network.clearBrowserCache");
        await page.goto("https://" + (this.usePlus ? "plus" : "beta") + ".character.ai");
        await page.evaluate(() => localStorage.clear());

        // If there is no waiting room, the script will continue anyway
        await this.waitForWaitingRoom(page);

        console.log("[node_characterai] Puppeteer - Done with setup");
        console.log("https://" + (this.usePlus ? "plus" : "beta") + ".character.ai")

    }

    async request(url, options) {
        const page = this.page;

        const method = options.method;

        const body = (method == "GET" ? {} : options.body);
        const headers = options.headers;

        let response;

        try {
            const payload = {
                method: method,
                headers: headers,
                body: body
            }

            await page.setRequestInterception(false);
            if (!this.#hasDisplayed) {
                console.log("[node_characterai] Puppeteer - Eval-fetching is an experimental feature and may be slower. Please report any issues on github")
                this.#hasDisplayed = true;
            }

            if (url.endsWith("/streaming/")) {
                // Bless @roogue & @drizzle-mizzle for the code here!
                response = await page.evaluate(async (payload, url) => {
                    const response = await fetch(url, payload);

                    const data = await response.text();
                    const matches = data.match(/\{.*\}/g);
                    const responseText = matches[matches.length - 1];

                    let result = {
                        code: 500
                    };

                    if (!matches) result = null;
                    else {
                        result.code = 200;
                        result.response = responseText;
                    };
                    return result;
                }, payload, url);

                response.status = () => response.code; // compatibilty reasons
                response.text = () => response.response; // compatibilty reasons
            } else {
                await page.setRequestInterception(true);
                let initialRequest = true;

                page.once("request", request => {
                    var data = {
                        "method": method,
                        "postData": body,
                        "headers": headers
                    };

                    if (request.isNavigationRequest() && !initialRequest) {
                        return request.abort();
                    }

                    try {
                        initialRequest = false;
                        request.continue(data);
                    } catch (error) {
                        console.log("[node_characterai] Puppeteer - Non fatal error: " + error);
                    }
                });
                response = await page.goto(url, { waitUntil: "domcontentloaded" });
            }
        } catch (error) {
            console.log("[node_characterai] Puppeteer - " + error)
        }

        return response;
    }

    async imageUpload(url, headers, localFile = false) {
        const page = this.page;

        let response

        try {
            await page.setRequestInterception(false);
            if (!this.#hasDisplayed) {
                console.log("[node_characterai] Puppeteer - Eval-fetching is an experimental feature and may be slower. Please report any issues on github")
                this.#hasDisplayed = true;
            }

            // The end of this repeated 2 times, is it intentional?
            // Can it be in the same spot at the end to avoid code repetition?
            if (localFile) {
                let dataUrl = fs.readFileSync(url, "base64");
                response = await page.evaluate(
                    async (uploadHeaders, dataUrl) => {
                            var result = {
                                code: 500
                            };

                            const b64toBlob = (b64Data, contentType = "", sliceSize = 512) => {
                                const byteCharacters = atob(b64Data); // <- Watch out, this is deprecated!
                                const byteArrays = [];

                                for (let offset = 0; offset < byteCharacters.length; offset += sliceSize) {
                                    const slice = byteCharacters.slice(offset, offset + sliceSize);

                                    const byteNumbers = new Array(slice.length);
                                    for (let i = 0; i < slice.length; i++) {
                                        byteNumbers[i] = slice.charCodeAt(i);
                                    }

                                    const byteArray = new Uint8Array(byteNumbers);
                                    byteArrays.push(byteArray);
                                }

                                const blob = new Blob(byteArrays, {
                                    type: contentType
                                });
                                return blob;
                            }

                            const blob = b64toBlob(dataUrl.includes("base64,") ? dataUrl.split("base64,")[1] : dataUrl);
                            const file = new File([blob], "image");
                            const formData = new FormData();
                            formData.append("image", file);

                            let head = uploadHeaders;
                            delete head["Content-Type"];
                            // ^ Is this even being used?

                            const uploadResponse = await fetch("https://" + (this.usePlus ? "plus" : "beta") + ".character.ai/chat/upload-image/", {
                                headers: uploadHeaders,
                                method: "POST",
                                body: formData
                            })

                            if (uploadResponse.status == 200) {
                                result.code = 200;

                                let uploadResponseJSON = await uploadResponse.json();
                                result.response = uploadResponseJSON.value;
                            }

                            return result;
                        },
                        headers, dataUrl
                );
            } else {
                response = await page.evaluate(
                    async (uploadHeaders, url) => {
                            var result = {
                                code: 500
                            };

                            const uploadResponse = await fetch(url).then(uploadResponse => uploadResponse.blob()).then(async (blob) => {
                                const file = new File([blob], "image");
                                const formData = new FormData();
                                formData.append("image", file);

                                let head = uploadHeaders;
                                delete head["Content-Type"];
                                // ^ Is this even being used?

                                const uploadResponse = await fetch("https://" + (this.usePlus ? "plus" : "beta") + ".character.ai/chat/upload-image/", {
                                    headers: uploadHeaders,
                                    method: "POST",
                                    body: formData
                                })
                                return uploadResponse;
                            }).then()

                            if (uploadResponse.status == 200) {
                                result.code = 200;

                                let uploadResponseJSON = await uploadResponse.json();
                                result.response = uploadResponseJSON.value;
                            }

                            return result;
                        },
                        headers, url
                );
            }

            response.status = () => response.code; // compatibilty reasons
            response.body = () => response.response; // compatibilty reasons
        } catch (error) {
            console.log("[node_characterai] Puppeteer - " + error)
        }

        return response;
    }

    async uninitialize() {
        // Handle chromium tabs cleanup
        try {
            this.browser.close();
        } catch {}
    }
};

module.exports = Requester;
`

**Comment by ftk789** [comment]
@Parking-Master Scuffed how I did it, But those 3 files.

**Comment by ftk789** [comment]
Is there a better way I can upload them? 3 files and all are long

**Comment by Parking-Master** [comment]
> Is there a better way I can upload them? 3 files and all are long
@ftk789 you could try opening a pull request yourself then. It's pretty easy.

- Fork this repository at the top of the website
- Change the specific files on the forked repo that you changed locally
- When done, go to "Pull requests" on the forked repo and click "Open pull request"
- Add a title and description, then wait for @realcoloride to merge it

Should be pretty straightforward. Let me know if you need any help.

**Comment by Parking-Master** [comment]
> Also i'm faceing an issue on how to get the " useplus " to be used on each file to determine the site.

Oh, yeah. I forgot about that. While I was updating the repo a few months ago I also ran into that issue. The `usePlus` variable is only used in `requester.js`. Some how, when requiring/importing the other files into the requester, you're gonna need to pass the default options (along with usePlus) into that require statement. Unfortunately that's the only way. Otherwise you'd need to combine all the files into one which realcoloride does not want.

**Comment by realcoloride** [comment]
You need to specify usePlus before initializing your client in the client.requester class.

**Comment by sivertheisholt** [comment]
This seems like the same problem related to #108 and #91 ? Character AI should really fix their API structure/domain, it's just bad.
