### ISSUE TITLE
Getting access token on mobile (Not issue, but a help)

### ISSUE THREAD

**Issue by gamersindo1223** [realcoloride/node_characterai#115]
Hi, if you are using a mobile device and can't get c.ai access token let me help you!
1. Go to https://c.ai
2. Make sure you are logged into your account
3. On the URL bar type `java` and paste this text `script:(function() { const c = Object.keys(window.localStorage).map(e=>{if(e.startsWith("@@")) return e}).filter(Boolean); if(!c.length) return alert("You need to login first!");document.documentElement.innerHTML = JSON.parse(window.localStorage[c]).body.access_token })()` 
4. After doing that you should have your entire page cahnged into your access token
5. just copy that token
6. Tada! Now you have your access token

**Comment by realcoloride** [comment]
This could be useful for mobile but since its not an issue, its best you make a [PR](https://github.com/realcoloride/node_characterai/pulls) to add this in the README.
Thanks for the suggestion though.
