### ISSUE TITLE
An `executablePath` or `channel` must be specified for `puppeteer-core`

### ISSUE THREAD

**Issue by Purp-le** [realcoloride/node_characterai#119]
ive seen a lot of issues in the github and i havent really found a solution
![image](https://github.com/realcoloride/node_characterai/assets/65814578/37ff818c-484d-4008-92d4-df7ccc0822e6)
just took the example code from the readme to see that everything worked and turns out it doesnt
![image](https://github.com/realcoloride/node_characterai/assets/65814578/f909a731-4438-42f3-abc4-7d21b23ca692)
it never fully reaches `Done with setup`
i do have everything installed im pretty sure (the node_characterai itself, node, chromium(?) and reinstalled puppeteer just in case)
there was [#110 (comment)](https://github.com/realcoloride/node_characterai/issues/110#issuecomment-1799248756), #86 but theyre not exactly the same error and as expected their solutions didnt work. ive went through probably every issue, closed and open, that *seemed* like it could be related but they didnt really help. any ideas?

**Comment by Purp-le** [comment]
nvm figured out the way of changing the path with `characterAI.requester.puppeteerPath = [chromium path]`

**Comment by realcoloride** [comment]
No problem. Happy coding!
