### ISSUE TITLE
IF YOU USER REPLIT READ THIS, ITS NOT ISSUES! TIPS FOR REPLIT USER

### ISSUE THREAD

**Issue by SGWNN** [realcoloride/node_characterai#121]
![Screenshot (57)](https://github.com/realcoloride/node_characterai/assets/151892929/70c16857-27c7-4696-acfc-26f7d535b900)

code character ai
`const CharacterAI = require("node_characterai");
const characterAI = new CharacterAI();
const { exec } = require("node:child_process");
const fs = require('fs').promises;
const { promisify } = require("node:util");

(async () => {
  const { stdout: chromiumPath } = await promisify(exec)("which chromium");
  //characterAI.puppeteerPath = await promisify(exec)("which chromium");
  characterAI.requester.puppeteerPath = '/nix/store/x205pbkd5xh5g4iv0g58xjla55has3cx-chromium-108.0.5359.94/bin/chromium-browser'
  //const setting = await promisify(exec)("which chromium");
  // Authenticating as a guest (use `.authenticateWithToken()` to use an account)
  await characterAI.authenticateAsGuest();

  // Place your character's id here
  const characterId = "8_1NyR8w1dOXmI1uWaieQcd147hecbdIK7CeEAIrdJw";

  const chat = await characterAI.createOrContinueChat(characterId);

  // Send a message
  const response = await chat.sendAndAwaitResponse("Hello discord mod!", true);

  console.log(response);
  // Use `response.text` to use it as a string
})();`

code for replit nix :

`{ pkgs }: {
	deps = [
    pkgs.nodePackages.typescript-language-server
    pkgs.yarn
    pkgs.replitPackages.jest
    pkgs.chromium
	];
}`

btw if its not working on you, chat me //sorry my english is bad, im from indonesian

**Comment by realcoloride** [comment]
Hey there, issues are not dedicated for this and this is not really related to the package but rather to Replit, which is a third party.

I recommend you push a [PR](https://github.com/realcoloride/node_characterai/pulls) and put some of that information in README.md if you believe it could help a lot of users.

Please re-open a new issue if you have any problems however.
Cheers
