### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by LordKaT** [realcoloride/node_characterai#127]
Ater logging in with cAI+ the API is returning a SyntaxError for me using the example app in the readme:

`name: 'SyntaxError',
  message: 'Bad string',
  at: 2,
  text: {
    window._cf_chl_opt = {
        cvId: '2',
        cZone: "plus.character.ai",
        cType: 'managed',
        cNounce: '',
        cRay: '',
        cHash: '',
        cUPMDTk: "\\/chat\\/streaming\\/?__cf_chl_tk=",
        cFPWv: 'g',
        cTTimeMs: '1000',
        cMTimeMs: '375000',
        cTplV: 5,
        cTplB: 'cf',
        cK: "visitor-time",
        fa: "\\/chat\\/streaming\\/?__cf_chl_f_tk=",
        md: "",
        cRq: {
            ru: '',
            ra: '',
            rm: '',
            d: '',
            t: '',
            cT: Math.floor(Date.now() / 1000),
            m: '',
            i1: '',
            i2: '',
            zh: '',
            uh: '',
            hh: '',
        }
    };
    var cpo = document.createElement('script');
    cpo.src = '/cdn-cgi/challenge-platform/h/g/orchestrate/chl_page/v1?ray=';
    window._cf_chl_opt.cOgUHash = location.hash === '' && location.href.indexOf('#') !== -1 ? '#' : location.hash;
    window._cf_chl_opt.cOgUQuery = location.search === '' && location.href.slice(0, location.href.length - window._cf_chl_opt.cOgUHash.length).indexOf('?') !== -1 ? '?' : location.search;
    if (window.history && window.history.replaceState) {
        var ogU = location.pathname + window._cf_chl_opt.cOgUQuery + window._cf_chl_opt.cOgUHash;
        history.replaceState(null, null, "\\/chat\\/streaming\\/?__cf_chl_rt_tk=" + window._cf_chl_opt.cOgUHash);
        cpo.onload = function() {
            history.replaceState(null, null, ogU);
        }
    }
    document.getElementsByTagName('head')[0].appendChild(cpo);
}()); < /script><script defer src="https:/ / static.cloudflareinsights.com / beacon.min.js / v84a3a4012de94ce1a686ba8c167c359c1696973893317 " integrity="
sha512 - euoFGowhlaLqXsPWQ48qSkBSCFs3DPRyiwVu3FjR96cMPx + Fr + gpWRhIafcHwqwCqWS42RZhIudOvEI + Ckf6MA == " data-cf-beacon='{"
rayId ":"
83 f76f06dba54d08 ","
version ":"
2023.10 .0 ","
token ":"
de6c8a8324c04a50b30bdeb96bc8d410 "}`

I stripped hashes/tokens I wasn't 100% sure should remain private or not from the reply.

Any ideas where I can look? Opening puppeteer in headless doesn't bring up any login screen or waiting rooms.

**Comment by realcoloride** [comment]
Sorry but I'm unsure of what is happening there. I do not have cai+ to debug. What function did you call for it to crash? 
I might know what the issue is though.

**Comment by LordKaT** [comment]
`try {
    const response = await chat.sendAndAwaitResponse("hello", true);
  } catch (err) {
    console.log(err);
  }`

If that doesn't help I can investigate this weekend when I'm not swamped with work.

**Comment by realcoloride** [comment]
Was it working before?

**Comment by LordKaT** [comment]
Unfortunately, I don't know. I just discovered this project today.

**Comment by realcoloride** [comment]
Okay, sorry for the inconvenience.
If you need to use the package currently, you can use the normal (not cai+) version in the meantime of a fix. There shouldn't be a waiting room.

**Comment by leonard3368** [comment]
I have the same error using guest and normal account. It worked before so maybe character ai changed something?

**Comment by realcoloride** [comment]
Could you send your full code perhaps?

**Comment by ChestnutKurisu** [comment]
Encountering the same error with cai+ (name: 'SyntaxError', message: 'Bad string'). My setup has been working well for the past five months and this is the first time I've seen this issue. Appeared for the first time $\approx$ 4 hours ago. 
Seems to be happening here (albeit my request is sent to the `plus.character.ai...` endpoint): https://github.com/realcoloride/node_characterai/blob/cfd791a45deac77e00c8ff655b34b7c17febe2f8/chat.js#L34. Code is similar to the one posted by @LordKaT.

**Comment by ChestnutKurisu** [comment]
Here is the code:
```javascript
if (process.argv.length > 3) {
    port = process.argv[3];
    character = process.argv[2];
}

await client.authenticateWithToken("<TOKEN>");
global.chatRoom = await client.createOrContinueChat(character);

async sendAndAwaitResponse(optionsOrMessage, singleReply) {
        if (!this.client.isAuthenticated()) throw Error('You must be authenticated to do this.');

        const payload = new OutgoingMessage(this, optionsOrMessage)
        const client = this.client;

        const request = await this.requester.request('https://plus.character.ai/chat/streaming/', {
            body: Parser.stringify(payload),
            method: 'POST',
            headers: client.getHeaders(),
            client: this.client
        }, true)

        console.log('https://plus.character.ai/chat/streaming/', {
            body: Parser.stringify(payload),
            method: 'POST',
            headers: client.getHeaders(),
            client: this.client});

        if (request.status() === 200) {
            // console.log(request);
            const response = await Parser.parseJSON(request);
            // console.log(`response: ${JSON.stringify(response)}`);

            const replies = response.replies;
            if (!replies) return [''];

            const messages = [];

            for (let i = 0; i < replies.length; i++) {
                messages.push(new Reply(this, response));
            }

            if (!singleReply) return messages;
            else return messages.pop();
        } else throw Error('Failed sending message.')
    }

wss.on('connection', (ws) => {
    console.log('A client connected');

    ws.on('message', async (message) => {
        if (!global.chatRoom) {
            console.log(`Unable to send message.`);
            console.log(`CharacterAI is still fetching character data!`);
            console.log(`If it's taking far too long please submit an issue.`);
            return;
        }

        let chatMessage = message.toString('utf8');

        try {
            const response = await global.chatRoom.sendAndAwaitResponse(chatMessage, true);
        } catch (err) {
            console.log(err);
        } 
        ws.send(`${response.text}`);
    });
});

**Comment by realcoloride** [comment]
Hello @ChestnutKurisu and thank you for this simple. While I cannot try this sample, I am waiting for OP to try it and say how it goes. If it goes well, I recommend you open a **PR** related to it.

Will try to merge and fix this issue for CAI+ users.

**Comment by realcoloride** [comment]
Hello @ChestnutKurisu, so you seem to be having the same problem aswell?

**Comment by ChestnutKurisu** [comment]
> 
> Hello @ChestnutKurisu, so you seem to be having the same problem aswell?
> 
> 

Yes, facing the same issue with my existing setup.

**Comment by realcoloride** [comment]
Could you try opening the Developer Tools, try sending a message and checking your network tab and see what request its pinging to?

I am pretty sure CAI+ has a different endpoint

**Comment by realcoloride** [comment]
Nevermind, it seems like I am beginning to have the same error aswell.
![image](https://github.com/realcoloride/node_characterai/assets/108619637/6d9757cb-bc87-456c-b5f6-63d686356232)

I will begin investigating on the issue.

**Comment by realcoloride** [comment]
![image](https://github.com/realcoloride/node_characterai/assets/108619637/9bad5b6f-e244-4677-9705-91f54e113d5f)
Update: I believe this might be a new character ai restriction in place...

**Comment by realcoloride** [comment]
Update: Setting to another user agent seem to have fixed it.

*in requester.js*
```js

        const userAgent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";
        await page.setUserAgent(userAgent);
```
![image](https://github.com/realcoloride/node_characterai/assets/108619637/9867309e-e621-4ed3-acf1-39ad82dccf17)

Waiting for your feedback/tests to start pushing a bugfix.

**Comment by ChestnutKurisu** [comment]
Thanks a bunch for the suggested fix! I'll check once I'm back at my laptop in a couple of hours and supply feedback.

**Comment by ChestnutKurisu** [comment]
Yes, I can confirm that changing the user agent did the trick. Thank you so much for the prompt response, @realcoloride! And also thanks for creating this wonderful project.

**Comment by LordKaT** [comment]
Changing the useragent appears to have worked too. Seems cAI enabled useragent string checking in their cloudflare implementation to reduce bot traffic.

**Comment by realcoloride** [comment]
Pushed commit https://github.com/realcoloride/node_characterai/commit/0752006059aa75aface8b1e4f1488fadc43d0faa and version `1.2.3`. **Remember to update often for more fixes or improvements.**

Happy coding!
*Please re-open an issue if you have other issues.*
