### ISSUE TITLE
Guest eval fetching no longer working after update

### ISSUE THREAD

**Issue by rishavpaul95** [realcoloride/node_characterai#128]
resource: the server responded with a status of 524 ()

**Comment by realcoloride** [comment]
Is your package up to date?

**Comment by rishavpaul95** [comment]
It seems characterAI guest responses are down. I am sorry for posting without checking.

**Comment by rishavpaul95** [comment]
Yes. Tokens are working. CharacterAI site is itself down. Servers are down on their end for guest users

**Comment by realcoloride** [comment]
After testing, it seems like the chatting (/streaming/) CharacterAI for guests is down. In the meantime, I recommend you use an access token or wait for it to become online again.

**Comment by rishavpaul95** [comment]
Thank you!

**Comment by realcoloride** [comment]
Update: the service seems to be back up.
