### ISSUE TITLE
Authentication token is invalid

### ISSUE THREAD

**Issue by min-808** [realcoloride/node_characterai#129]
For the past week or so, I was able to successfully connect to c.ai using the API. However, today out of the blue I got an error saying that the authentication token is invalid. I tried making a new account and using a new token, but I still got the same error

```
Error: Authentication token is invalid
    at Client.authenticateWithToken (C:\...\node_modules\node_characterai\client.js:227:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.run (C:\...\chat.js:41:21)
```

**Comment by 3vil3vo** [comment]
Same error

**Comment by handoko19** [comment]
+1

**Comment by realcoloride** [comment]
Weird, I will investigate on this issue.

**Comment by realcoloride** [comment]
![image](https://github.com/realcoloride/node_characterai/assets/108619637/408510cf-07d7-42b2-8b3b-b468c6e52044)
Update: there seems to be two values to login now.

**Comment by realcoloride** [comment]
Second Update: after adding the id token parameter, it seems to work again.
![image](https://github.com/realcoloride/node_characterai/assets/108619637/757325fc-6996-4353-bb10-e400cba16e40)

This means that I will have to add an update in the documentation about this information.
If you urgently need to use your package, see this commit: https://github.com/realcoloride/node_characterai/commit/d84afce96527cd217b3e261da9dc991c9a1ebb4e

I added a temporary error message:
![image](https://github.com/realcoloride/node_characterai/assets/108619637/28c58e6a-ea2a-46b2-995f-64120ec0c0e4)

To get the id token, it should be the same way you get the authentication token.

**I will make an update to the README.md soon.*

**Comment by realcoloride** [comment]
Pushed this commit to update README.md: https://github.com/realcoloride/node_characterai/commit/f2ad12999820e74f66c6544f67f6c25514d84551

Please update me on how the update went for you. If it works, I will push it to the package.

**Comment by min-808** [comment]
It works after including the new id_token. Thank you for the quick fix!

**Comment by realcoloride** [comment]
No problem, I will push the update to npm soon.

**Comment by 3vil3vo** [comment]
Thank you! Works perfectly fine. Good job.

**Comment by realcoloride** [comment]
Pushed update `1.2.4`. Please feel free to re-open a issue if the problems persist.
