### ISSUE TITLE
Puppeteer timeout error

### ISSUE THREAD

**Issue by IRON-M4N** [realcoloride/node_characterai#132]
So i made it into a express api and sometimes it gives this error. 

_Error: waiting for target failed: timeout 30000ms exceeded
Error: Protocol error (Network.setUserAgentOverride): Session closed. Most likely the page has been closed._

**Comment by realcoloride** [comment]
Hello, could you provide more details? Code, line that failed, additional context like your environment, the package version...

**Comment by IRON-M4N** [comment]
I'm encountering this issue i deployed it on Railway.
Initially, it works well for the first 4-5 requests, but then I receive the following error

_(node:7) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added to [process]. Use emitter.setMaxListeners() to increase the limit_

_(Use `node --trace-warnings ...` to show where the warning was created)_


If you could provide your contact information, I'll be able to share the code with you.

**Comment by realcoloride** [comment]
Hello, this error means you are doing too many `event.on` without doing `event.off()` to delete the event, causing a memory leak.
