### ISSUE TITLE
On server, Chromium path for puppeteer could not be located

### ISSUE THREAD

**Issue by JasonARong** [realcoloride/node_characterai#138]
The code works perfectly fine on my local machine (Mac). However after I deployed it to the google cloud, it returns the following warning and error.
<img width="1077" alt="Screen Shot 2024-01-25 at 2 32 19 PM" src="https://github.com/realcoloride/node_characterai/assets/121317929/7f5f539d-e39f-4f5c-91de-3b2e770399e8">
<img width="1064" alt="Screen Shot 2024-01-25 at 2 32 39 PM" src="https://github.com/realcoloride/node_characterai/assets/121317929/1304fc24-be3d-489d-a90e-1a618b6d3f1d">

I realized there was a similar problem in issue #86 , but it seems like the solutions was just for Linux.

**Comment by realcoloride** [comment]
See https://github.com/realcoloride/node_characterai?tab=readme-ov-file#troubleshooting.
