### ISSUE TITLE
No tokens available

### ISSUE THREAD

**Issue by bazhenberg** [realcoloride/node_characterai#139]
Hello! I have lost the Token ID and the token itself. At the same time, I am still an authorized user.
<img width="1390" alt="Screenshot_16" src="https://github.com/realcoloride/node_characterai/assets/17933558/6339e223-cbb8-443e-a310-4f85a5d7f54a">

**Comment by realcoloride** [comment]
Try going in the home page (https://beta.character.ai/) and checking localstorage.

**Comment by bazhenberg** [comment]
<img width="1920" alt="2 PNG" src="https://github.com/realcoloride/node_characterai/assets/17933558/58038981-f038-4970-ba32-656db5cba067">

**Comment by realcoloride** [comment]
I'm not quite sure what is happening here.. 
Could you try logging in on Chrome and see instead?

## But here is a lackluster solution that could help if switching to Chrome (or similar) doesn't work:

Step 1. Open a new tab.
Step 2. Open developer tools and go to the **network** tab.
Step 3. Make sure the requests are being recorded then click **Fetch/XHR**.
![image](https://github.com/realcoloride/node_characterai/assets/108619637/e63f2436-2f81-4d69-80b8-e3bdcbe7ef26)
Step 4. Open up CharacterAI.
Step 5. Go in **Application** > search for the `char_token` key.
![image](https://github.com/realcoloride/node_characterai/assets/108619637/afcbcd51-745b-4685-a950-57b479dc25f4)
Step 6. If you see it, **right click** it and **delete it**. *This will ensure to log your session off to generate a new token.*
![image](https://github.com/realcoloride/node_characterai/assets/108619637/e79fc06e-a05e-4822-9245-072a71e30ce7)
Step 7. Head back to the **network** tab.
Step 8. Refresh the page.
Step 9. Locate the `auth0/` endpoint request.
![image](https://github.com/realcoloride/node_characterai/assets/108619637/772e0ddd-270a-410a-be6e-00ebf37a7f54)
Step 10. Examine the request. From there you will have an access_token and id_token. Right click to individually copy the access OR id token.
![image](https://github.com/realcoloride/node_characterai/assets/108619637/b3510ec7-2899-45e8-af6f-eca0d3c78366)

Good luck.

**Comment by Edenyaw** [comment]
> I'm not quite sure what is happening here.. Could you try logging in on Chrome and see instead?
> 
> ## But here is a lackluster solution that could help if switching to Chrome (or similar) doesn't work:
> Step 1. Open a new tab. Step 2. Open developer tools and go to the **network** tab. Step 3. Make sure the requests are being recorded then click **Fetch/XHR**. ![image](https://private-user-images.githubusercontent.com/108619637/300066093-e63f2436-2f81-4d69-80b8-e3bdcbe7ef26.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1NjIwNjEsIm5iZiI6MTcwNjU2MTc2MSwicGF0aCI6Ii8xMDg2MTk2MzcvMzAwMDY2MDkzLWU2M2YyNDM2LTJmODEtNGQ2OS04MGI4LWUzYmRjYmU3ZWYyNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyOVQyMDU2MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNjRiMjAwMDE2YTU3ZDE5ZmEwNDkyNGI3MTk1NTVmODZjNDc3ODZjY2M0YmI4ZjY0MDk1MGRlZmU2YTU5YjYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.djr0S7DSTwrFkmdYuT76t8XDbRetexYCqBAJplGN5Po) Step 4. Open up CharacterAI. Step 5. Go in **Application** > search for the `char_token` key. ![image](https://private-user-images.githubusercontent.com/108619637/300067757-afcbcd51-745b-4685-a950-57b479dc25f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1NjIwNjEsIm5iZiI6MTcwNjU2MTc2MSwicGF0aCI6Ii8xMDg2MTk2MzcvMzAwMDY3NzU3LWFmY2JjZDUxLTc0NWItNDY4NS1hOTUwLTU3YjQ3OWRjMjVmNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyOVQyMDU2MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMDAxZjFlMmQzOTc3YjQxNzkwNTg4ZmRjNjkxNmIzMmYzZWEwOWI2Mzk0M2FkN2M0N2U1NjQ3YWI5YWNmMTk5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9A9_55DTxyZ9o3HANSlxV49wSg6tQaOl9M5_IZ2vCsM) Step 6. If you see it, **right click** it and **delete it**. _This will ensure to log your session off to generate a new token._ ![image](https://private-user-images.githubusercontent.com/108619637/300067898-e79fc06e-a05e-4822-9245-072a71e30ce7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1NjIwNjEsIm5iZiI6MTcwNjU2MTc2MSwicGF0aCI6Ii8xMDg2MTk2MzcvMzAwMDY3ODk4LWU3OWZjMDZlLWEwNWUtNDgyMi05MjQ1LTA3MmE3MWUzMGNlNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyOVQyMDU2MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MDcwZjMyYWNjMjc1MjRkZTAyMzE0M2IwZGUwZTZhNGZkYjgxMTYzZGJmNjZmNzgyOTQ2YjAxMGY0MjRiYTdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.to7mQ2vbRpcb5Eg28LqtX17K8LmfnxIqLQIZU4aqdhw) Step 7. Head back to the **network** tab. Step 8. Refresh the page. Step 9. Locate the `auth0/` endpoint request. ![image](https://private-user-images.githubusercontent.com/108619637/300068085-772e0ddd-270a-410a-be6e-00ebf37a7f54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1NjIwNjEsIm5iZiI6MTcwNjU2MTc2MSwicGF0aCI6Ii8xMDg2MTk2MzcvMzAwMDY4MDg1LTc3MmUwZGRkLTI3MGEtNDEwYS1iZTZlLTAwZWJmMzdhN2Y1NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyOVQyMDU2MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZjY2N2UxZGYxNmNkMzUwZTgzYjlkYjk4YzM4NWYwNDdiYTgwNTUyNDY4NmVjYjJmNzJhZjM4NjBmNjQ3OTY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dHDOy_u2czZ08t4ETLbKj9C68BufN3p4y7UtnxO-gIY) Step 10. Examine the request. From there you will have an access_token and id_token. Right click to individually copy the access OR id token. ![image](https://private-user-images.githubusercontent.com/108619637/300068197-b3510ec7-2899-45e8-af6f-eca0d3c78366.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1NjIwNjEsIm5iZiI6MTcwNjU2MTc2MSwicGF0aCI6Ii8xMDg2MTk2MzcvMzAwMDY4MTk3LWIzNTEwZWM3LTI4OTktNDVlOC1hZjZmLWVjYTBkM2M3ODM2Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyOVQyMDU2MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOTMzNWU2NzcxYzc0NDMyMWYyZWQyZjU4MDc0ODc5NzkzNzJiYmU4ZTc5M2IxZDJlNjc3ODgwYTc2ZmJkZWY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.U7TwYsvAJMhGYnqC0HCDjJzp8n_DGdSOHMzN-O7Zoag)
> 
> Good luck.

Hey,
I can't find the tokens like the author and I tried doing what you wrote here but I can't find the auth0/ in the network tab still.. it's a bit weird because I've had them before, then I logged out and logged back in and I haven't been able to see them there since then.. I wonder why
hope you have a good day sorry for bothering!

**Comment by realcoloride** [comment]
Hello, I don't really know how to help you here then. 
Make sure you are on the home page (https://beta.character.ai/) and you delete the char_token key and continue with the steps.

**Comment by Edenyaw** [comment]
> Hello, I don't really know how to help you here then. Make sure you are on the home page (https://beta.character.ai/) and you delete the char_token key and continue with the steps.

Ye I made sure but nothing unfortunately
Thank you anyways appreciate it!

**Comment by realcoloride** [comment]
No problem, and again I'm sorry. If really needed, try changing to another browser, or try getting the token in network requests and hardcoding it from source but since they expire its not super long term.

Good luck again.

**Comment by realcoloride** [comment]
Hi there, check out #146
