### ISSUE TITLE
There is no access token and id token

### ISSUE THREAD

**Issue by amirhsy82** [realcoloride/node_characterai#141]
![Screenshot (227)](https://github.com/realcoloride/node_characterai/assets/125390977/9db70c95-a98a-4eb4-ba42-29ddd07d011a)

Hi. I have done the instructions but I can't find the access and id token.

**Comment by realcoloride** [comment]
See https://github.com/realcoloride/node_characterai/issues/134 and https://github.com/realcoloride/node_characterai/issues/139

**Comment by realcoloride** [comment]
Hi there, check out #146
