### ISSUE TITLE
authentication issue on replit

### ISSUE THREAD

**Issue by Asphyxiav2** [realcoloride/node_characterai#142]
keeps showing need authentication even though I already put the 2 tokens

**Comment by realcoloride** [comment]
Hello,
Please describe more information about your issue.

**Comment by Hadestia** [comment]
I daresay your script consistently invokes the '.authenticateToken' function whenever an execution commences. I suggest to write it outside that script and past it as parameter.

**Comment by Asphyxiav2** [comment]
For some reason even after I put the id and access tokens it still gives the "You must be authenticated to do this." When I'm trying to use the command. I'm a newbie in programming so I don't know a lot about the errors.

Here's the pastebin link
https://pastebin.com/krBumUVN

**Comment by realcoloride** [comment]
This is an issue related to character ai as they have swapped the way authenticating works, I am still investigating on a way to fix this and make it work. I have so far figured how to do google logins, I will keep you updated. For now, use guest accounts until I find a proper fix. Sorry.

**Comment by realcoloride** [comment]
See #146, this should have been fixed now.

**Comment by Asphyxiav2** [comment]
So normal way would work if I use account other than Google account?
