### ISSUE TITLE
#Client.generateImage() result link appears to be unavailable 

### ISSUE THREAD

**Issue by Hadestia** [realcoloride/node_characterai#143]
Hello, I attempted to utilize this function, however it appears the returnable URL is routinely closed or deleted upon retrieval, resulting in an error 404 advising the page is unavailable. When I attempted to view the returned URL via my browser, it rendered a similar outcome. Is there a possibility of a faulty parameter?
![Screenshot_20240129-182935_1](https://github.com/realcoloride/node_characterai/assets/89353591/979bc3ac-e240-4110-97f4-d7b0d091fcee)

**Comment by realcoloride** [comment]
Hello, could you show me your code,

**Comment by Hadestia** [comment]
I was wrong it's because of the cloudflare not letting my fetcher to get the image data. Is there should be a possibility that we could do 'pipe' the returned link?

**Comment by Hadestia** [comment]
Sorry I'm developing with my Android
![Screenshot_20240129-185615_1](https://github.com/realcoloride/node_characterai/assets/89353591/d8b36834-50c5-401a-bf20-83fda084616e)
 but here's my code, while 'Utils.downloadFile' was just an 'Axios.get()' function

**Comment by realcoloride** [comment]
Hello, your code seem correct, but perhaps downloadFile is faulty. Try to open the generated image in characterai's UI and your browser and see if they show up correctly. If not, try analyzing the chromium's browser requests. set headless to false and search for the generate request in the Network tab and see the response you get.

Good luck and keep me updated!

**Comment by realcoloride** [comment]
Hello, the image uploading features were rewritten since.

Feel free to re open an issue or this one if you encounter more or the same problem.
Cheers.
