### ISSUE TITLE
Converting circular structure to JSON     --> starting at object with constructor 'Browser'     |     property '_defaultContext' -> object with constructor 'BrowserContext'     --- property '_browser' closes the circle Are you passing a nested JSHandle?

### ISSUE THREAD

**Issue by LuckyIndraEfendi** [realcoloride/node_characterai#145]
![Screenshot from 2024-02-03 21-54-32](https://github.com/realcoloride/node_characterai/assets/90430786/0add5b61-baf8-4941-ad7a-9b452b475c54)

**Comment by LuckyIndraEfendi** [comment]
Please Help me fix it

**Comment by realcoloride** [comment]
Hello, this is an error related the puppeteer package and not node_characterai. Please try reinstalling the package or open a relevant issue on their end. I will then close this issue but feel free to re-open or make a new one if you have any related node_characterai issues.
