### ISSUE TITLE
Authentication methods changed

### ISSUE THREAD

**Issue by realcoloride** [realcoloride/node_characterai#146]
Hello,

For the second time, it seems like characterai has switched to a new way of authentication.

**Comment by realcoloride** [comment]
From my search, it seems like atleast for google accounts, there is an id tokenand key associated with a token from the new endpoint of dj-rest-auth/google_idp/.
![image](https://github.com/realcoloride/node_characterai/assets/108619637/21a3c51e-9262-4a52-a568-25eb098d1511)

This produces a session token.
![image](https://github.com/realcoloride/node_characterai/assets/108619637/1c087a13-5863-45ba-8c7d-4d08bec9d01d)

This is the endpoint in question.
![image](https://github.com/realcoloride/node_characterai/assets/108619637/f6f7efa6-a816-455f-ab1b-c16757b3e5b4)

For easier development purposes, I might have to switch to using the session token only and rework the README.md.
![image](https://github.com/realcoloride/node_characterai/assets/108619637/7e5701a7-c23b-426d-b86c-b840e22a3026)

I will keep you updated.

**Comment by realcoloride** [comment]
Hello again,
![image](https://github.com/realcoloride/node_characterai/assets/108619637/3058bfec-0a12-4690-8c5e-06ff8f34a060)

Changing to char_token seems to be a viable solution. I will push a fix along with the readme.md tutorial soon.

**Comment by realcoloride** [comment]
I added a warning message if the token is not as the same size of char_tokens (40).
![image](https://github.com/realcoloride/node_characterai/assets/108619637/d0049815-7ab5-482c-93a6-ad6d3eba18de)

**Comment by realcoloride** [comment]
Relevant commits:
https://github.com/realcoloride/node_characterai/commit/7cb8e59a241049edbb7d0183c31feeed5d1b7f37 and https://github.com/realcoloride/node_characterai/commit/46db79ec79e58e36e326130060fc512dae0abfb5.

Experimental version `1.2.5` was pushed, please let me know how it goes for you all.

**Comment by Asphyxiav2** [comment]
![Screenshot_20240205-233206](https://github.com/realcoloride/node_characterai/assets/155067655/b310aa0f-9396-40cb-9423-8ad8d5ee58df)
No id token

**Comment by realcoloride** [comment]
Hello, please read the entire issue. Id tokens and access tokens have been replaced with session tokens. See README.md.

**Comment by azureknight63** [comment]
Thanks for the update. Your changes seem to be effective. For the readme update, it seems that the access token is now under Local Storage > char_token.value as you described. The ID token is under Local Storage > uuid. 

It also looks like char_token has a 1-month TTL property. It's hard to suggest a feature if character.ai is going to change authentication methods this frequently, but if it stabilizes then I would recommend including utility for updating the char_token.

Cheers.

**Comment by realcoloride** [comment]
I seem to have also detected that the newer chat interface uses a websocket whilst the old interface uses good old requests.
Might be interesting to open an issue related to it.

**Comment by ameshkin** [comment]
I believe things may have changed again. I can't seem to find the right tokens in the local storage.

**Comment by realcoloride** [comment]
Hello there, open up dev tools, try going in the "Network" tab when opening dev tools, and filter by `Fetch/XHR`.

![image](https://github.com/user-attachments/assets/1273b44a-6f59-458b-873c-9c8beed29574)

Then, open up any conversation. You'll see something like this.

![image](https://github.com/user-attachments/assets/c7b14c44-4616-4fd3-b357-2475f505bf2b)

Click in one of the requests, and look for the Authorization key.
![image](https://github.com/user-attachments/assets/389b1e0e-7726-4420-a721-4cc012e79906)

Then, look for the Authorization key. Whatever comes after "Token " is what you are looking for.

Cheers

**Comment by Pratik-Singh335** [comment]
I can't find the Character.AI  auth token help

**Comment by realcoloride** [comment]
Still need help?

**Comment by lankze** [comment]
> Still need help?

can the token expire and need to be regenerated?
