### ISSUE TITLE
Can i get avatar picture from character?

### ISSUE THREAD

**Issue by Vernityz** [realcoloride/node_characterai#148]
hello i am new to coding.
example: `const response = wait chat.sendAndAwaitResponse("hello", true)`
when I check the console the result is "hello....."
but i need to add `response.text` to return as a string, well. my question is, can we get the avatar url or name of the character we are talking with?

example: `response.avarar_url` or `response.username` ?
or does this have its own function?

**Comment by realcoloride** [comment]
Hello, you can use `fetchCharacterInfo(characterId);`  for this.
