### ISSUE TITLE
New Chat session

### ISSUE THREAD

**Issue by asdgggg** [realcoloride/node_characterai#149]
Hi, thanks for this! Anyway, how do I start a new chat? Because I am trying to fine tune my waifu, it does work on the website chat but waifu is using an old chat so the changes don't affect her. How to do this? Thanks

**Comment by realcoloride** [comment]
Hello,

About the old UI switch, I don't exactly know why it happens but if you
wish to  "fine tune" your best attempt is to change your persona on the
website and create your own character.

Fine tuning via messages will not work properly or last long enough from
experience and using out of character forcing not either. It seems like the
ai tried to be as similar as possible from it's character prompt (I'd
suggest it's also in the parameters of the model itself).

But for your complete answer, perhaps I suggest you should try sending
messages manually and programmatically. If you wish to switch to the old
chat, rename chat2 to chat in the url.

Cheers.

**Comment by asdgggg** [comment]
> Hello, About the old UI switch...

Hi, thanks for the response, this is not what I wanted though :) I am changing the persona frequently and then testing its responses. I am not 'fine tuning' in the chat, I am doing it in the character/persona/whatever page just like it should be done. 

The problem is when I turn my AI on it continues using an old version of the chat (the bot is not updated with edited descriptions etc.) instead of creating a new chat. Does that make sense? If I chat with my bot through the desktop waifu, then turn it off and leave it off for a week, then turn it on again, the chat continues where we left it instead of starting from a new one. I think that in some cases this may be a feature but for me it's a bug. The session token doesn't update, I tried relogging, reopening the website etc. but the session token stays the same, I thought maybe that would change but no.

But I guess making an entirely new character would be the easiest in my case.

**Comment by realcoloride** [comment]
Hello and sorry for the late response,
The new chat seems to be using a websocket to communicate whilst the old chat uses requests, which is why they differ from each other.

I might work on an update that allows you to switch between websockets and requests, but that could break compatibility.

**Comment by PasanSilva99** [comment]
Any update on this?

**Comment by realcoloride** [comment]
No not yet. I plan on switching to the new websocket interface as late as possible to avoid breaking compatibility.

**Comment by realcoloride** [comment]
Hello again, I might change my mind now. #180
