### ISSUE TITLE
Error, fetch is not defined.

### ISSUE THREAD

**Issue by Nessie-Dev** [realcoloride/node_characterai#15]
is says fetch is not defined. I'm using node js 16, please help me how can i fix this?

**Comment by realcoloride** [comment]
Use node version 18 or higher.

**Comment by Naozumi520** [comment]
I'm using node 18 and getting the same problem. I'm hosting on heroku.

<img width="1194" alt="Screenshot 2023-03-13 at 8 20 03 PM" src="https://user-images.githubusercontent.com/52615455/224700087-200dc929-322f-4bba-8d92-b7ea6b1d5679.png">

**Comment by realcoloride** [comment]
See old issues(they address the same problem) try installing cross fetch.

**Comment by Nessie-Dev** [comment]
No bro using node js version 18 will affect my all scripts plugins. Please any other way to fix this?

**Comment by realcoloride** [comment]
Update 1 - Related to issue #11, quote:
> I upgraded to v18 so for me it's not a problem anymore. But if you want to make it compatible with older versions, you could just use the node-fetch library instead. All you have to do is import it.

![image](https://user-images.githubusercontent.com/108619637/224763265-6bfd264c-bad6-4502-a1ad-d421305c3320.png)

After checking, node-fetch is already required in the dependencies. (in 1.0.0 at least)

**Comment by realcoloride** [comment]
Merging all updates for `1.1.1` in a new issue: #17.
Thank you for your understanding and patience.
