### ISSUE TITLE
The example code in README.md throws an Error

### ISSUE THREAD

**Issue by SeoulSKY** [realcoloride/node_characterai#155]
Version: 1.2.5

I tried to run the code in README.md

```typescript
  const characterAI = new CharacterAI();
  await characterAI.authenticateAsGuest();

  // Place your character's id here
  const characterId = "8_1NyR8w1dOXmI1uWaieQcd147hecbdIK7CeEAIrdJw";

  const chat = await characterAI.createOrContinueChat(characterId);

  // Send a message
  const response = await chat.sendAndAwaitResponse(
      "Hello discord mod!",
      true
  );
```

But I get the following exception

```bash
Traceback:

/Users/swkim7519/Desktop/SoruSora/sorusora-ai/node_modules/node_characterai/chat.js:70
            for (let i = 0; i < replies.length; i++) {
                                        ^
TypeError: Cannot read properties of undefined (reading 'length')
    at Chat.sendAndAwaitResponse (/Users/swkim7519/Desktop/SoruSora/sorusora-ai/node_modules/node_characterai/chat.js:70:41)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

When I debug the `Chat.sendAndAwaitResponse()`, the `request.code` is `200` and the `response` object is the following:
```
{
  "force_login": true
}
```
So, the issue is that the `response.replies` is `undefined` and it tries to get `length` properly from `undefined`

**Comment by SeoulSKY** [comment]
Changing authenticateAsGuest() with authenticateWithToken() fixes the problem. I believe there is a problem in authenticateAsGuest()

**Comment by realcoloride** [comment]
Hello, judging by how it looks, it seems like CharacterAI might have changed the way authentication for guests work.

I will investigate and let you know.

**Comment by realcoloride** [comment]
Hello,

this is an intended error and nothing is wrong. Force login means you've reached the quota of messages. Sadly it looks like characterAI has restricted guests users.

**Comment by codeblitz97** [comment]
@realcoloride restricted? Means we can no longer authenticate as guests?

**Comment by realcoloride** [comment]
Exactly. Try opening CharacterAI in an incognito tab and see how they restrict you from the first message.

**Comment by codeblitz97** [comment]
Wow, character ai seriously removed guest authentication system, it's not a big issue though

**Comment by SeoulSKY** [comment]
@realcoloride It's odd that I got this error because I ran the code for the first time. Anyway, if authenticateAsGuest() no longer works, I think you should modify the example code in README.md because people might think your library no longer works. Thank you for the clarification!

**Comment by realcoloride** [comment]
They do these kinds of unprevented things here and then sometimes. Sorry.

They might restore it soon, though. I will not change the README.md because it happened before and they restored the guest logins shortly. So just in case, if they get the problem, they shall see or open an issue and I will redirect them.

**Comment by realcoloride** [comment]
> least throw a custom error that the function no longer works

I will not make that but I will definitely make an exception.

**Comment by SeoulSKY** [comment]
> sorry for the incovenience!

No worries. I appreciate your hard work, and totally understand that this kind of problem might happen frequently with using their unofficial API.

**Comment by realcoloride** [comment]
Hello, I have commited https://github.com/realcoloride/node_characterai/commit/144f2bb9b5cabfa514e0c9b1b0c4520223e1d0d1 and experimental version `1.2.7` has been pushed. Please let me know if you get a proper error now.

**Comment by SeoulSKY** [comment]
> Please let me know if you get a proper error now.

It now throws a proper error with authenticateAsGuest() :)
```
Error: Too many messages! (this might be because you use a guest account or that characterai has restricted messages for guests.)
    at new Reply (/Users/swkim7519/Desktop/SoruSora/sorusora-ai/node_modules/node_characterai/message.js:119:48)
    at Chat.sendAndAwaitResponse (/Users/swkim7519/Desktop/SoruSora/sorusora-ai/node_modules/node_characterai/chat.js:68:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

```
