### ISSUE TITLE
Error with history

### ISSUE THREAD

**Issue by BlaBlak2** [realcoloride/node_characterai#156]
When using history, I am getting an error from this line in chat.js

```
const ai = continueBody.participants.find((participant) => participant.is_human === false);
```

The error:
```
[node_characterai] Puppeteer - Done with setup
[node_characterai] Puppeteer - Eval-fetching is an experimental feature and may be slower. Please report any issues on github
Error:  TypeError: Cannot read properties of undefined (reading 'find')
```

My code:

```
const CAI = require('node_characterai');
const client = new CAI();
await client.authenticateWithToken('token');
const chat = await client.createOrContinueChat('char id', 'hist id);
const response = await chat.sendAndAwaitResponse("Hey!", true);
console.log(response.text)
```

This only happens when I use history.

**Comment by BlaBlak2** [comment]
Found another thing, the history it created has the (I think old fashion version) id different, it looks more like a character id than a history id

**Comment by realcoloride** [comment]
Hello, I will investigate on this issue.

As of chat v2 (neo), I will think of it. This could probably cause some compatibility issues with older versions but I think it might be benefic. However, it could require for me to do a big rewrite.

Cheers
