### ISSUE TITLE
403 on createOrContinueChat

### ISSUE THREAD

**Issue by moon91210** [realcoloride/node_characterai#16]
Ever since last night the API has stopped working, speficially on createOrContinueChat where you get ``TypeError: Cannot read properties of undefined (reading 'characterId')`` on the returned chat.
I checked the request that is made and turns out it's getting a 403 error, indicating that it's probably not authenticated properly.

I think C.AI has pushed an update that caused it to break.

**Comment by moon91210** [comment]
Pretty sure C.AI has increased their security against bots. I added a user agent and got a Cloudflare 1020 error.
This is what's in the response html:
```html
<div class="cf-error-title">
   <h1>Access denied</h1>
   <span class="cf-code-label">Error code <span>1020</span></span>
</div>
<div class="cf-error-description">
   <p>You do not have access to beta.character.ai.</p><p>The site owner may have set restrictions that prevent you from accessing the site.</p>
</div>
```

**Comment by realcoloride** [comment]
Merging all updates for `1.1.1` in a new issue: #17.
Thank you for your understanding and patience.
