### ISSUE TITLE
Cannot statically analyse 'require(…, …)' in line 11

### ISSUE THREAD

**Issue by mahfuz0001** [realcoloride/node_characterai#163]
Hii. Im using nextjs with typescript and getting this  error while using this package

![image](https://github.com/realcoloride/node_characterai/assets/133667226/f4a4e07d-ea46-499a-ba0f-e58e15736a65)

![image](https://github.com/realcoloride/node_characterai/assets/133667226/e357bc16-b5d7-4468-8a65-4a0a481a859f)

**Comment by realcoloride** [comment]
Hello! This is not an issue related to the node_characterai package, but here is a provided fix that could help you perhaps: https://stackoverflow.com/a/76999195
![image](https://github.com/realcoloride/node_characterai/assets/108619637/e509fff1-1f11-4dd2-b29e-242ce2a44c05)

Cheers and good luck.
