### ISSUE TITLE
Character AI - New TTS system

### ISSUE THREAD

**Issue by sivertheisholt** [realcoloride/node_characterai#167]
They have added a new TTS system, where you can create custom voices or use other voices/predefined voices.
Would be cool if we could implement this. The current implementation is only able to fetch and use the old voices.

https://blog.character.ai/character-voice-for-everyone/

Any thoughts on this? I will take a look at it and see how it works.

**Comment by realcoloride** [comment]
µµ_This is honestly super uncanny and scary_µµ but how does the format work? is it a file? is it streamed audio?

**Comment by sivertheisholt** [comment]
> **_This is honestly super uncanny and scary_** but how does the format work? is it a file? is it streamed audio?

From what I have tried you can upload an audio file with 10-15 seconds of talking. It is scary accurate...

**Comment by realcoloride** [comment]
> > **_This is honestly super uncanny and scary_** but how does the format work? is it a file? is it streamed audio?
> 
> From what I have tried you can upload an audio file with 10-15 seconds of talking. It is scary accurate...

The google funding must have been crazy but hell no I am not uploading any audio 😭

**Comment by IRON-M4N** [comment]
So, I cloned the voice of Furina (a character from Genshin Impact) using this audio sample: https://i.imgur.com/Wb9XuG3.mp4

I tried c.ai and play.ht for comparison. The character AI cloning was way faster and sometimes sounded identical to the real one.

Play.ht cloning is really good but sometimes it glitches the voice.

I think it would be a cool feature to use the cloned voices in the module.

**Comment by realcoloride** [comment]
Will look into it

**Comment by realcoloride** [comment]
![image](https://github.com/realcoloride/node_characterai/assets/108619637/6565428a-d6bf-43ab-be6c-988de1da9e1a)
Ok so I have no idea what the format of the data is, but the domain is used in joinOrCreateSession to create an rtc session.

![image](https://github.com/realcoloride/node_characterai/assets/108619637/53624f63-23f2-4e2f-a8be-e1ffeb0a840f)
Now i'd actually be surprised if it REALLY opened a webrtc session to do this, but i'll investigate more

for fetching the voices it should be easy, they have a domain for it.

**Comment by Jatinverma0786** [comment]
Any update brother about voice system?

**Comment by realcoloride** [comment]
Hello,

Not really. I haven't looked for it since but if I have interest and this is a feature a lot of developers would like to see on the package feel free to let me know.

Cheers

**Comment by Jatinverma0786** [comment]
> Hello,
> 
> Not really. I haven't looked for it since but if I have interest and this is a feature a lot of developers would like to see on the package feel free to let me know.
> 
> Cheers

I think this feature will be the most demanding feature as I am also a developer and I need this feature so hardly so I request you to work on it please

**Comment by wolfboss356** [comment]
I also request that you to work on it. I'm an animatronic developer, and using premade Character AI TTS would save me a lot of time wrangling Mozilla TTS and installing a custom dataset on it.

**Comment by realcoloride** [comment]
After investigation, implementing this feature would mean to rework the entire endpoints to switch to the new (neo) endpoints and switch to a websocket etc.

**Comment by Jatinverma0786** [comment]
> After investigation, implementing this feature would mean to rework the entire endpoints to switch to the new (neo) endpoints and switch to a websocket etc.

So you will work on it or not brother or you need help in coding part?

**Comment by realcoloride** [comment]
I think I might have to consider both. I am considering rewriting and upgrading to the new API. Will let you know, I am very busy right now. 

Cheers :)

**Comment by keyserjaya** [comment]
Omg, didn't expect it using livekit. It likes we are really chatting with someone :D
Maybe you have some clues to share to make it works? 

Maybe some of us can help.

**Comment by realcoloride** [comment]
[Hey there, this should help](https://github.com/realcoloride/node_characterai/issues/167#issuecomment-2083456945)

However switching to the new endpoints require a total rewrite of the client

**Comment by Jatinverma0786** [comment]
I have foundout that Character.AI is using EdgeTTS LOL

**Comment by yukiarimo** [comment]
Any updates?

**Comment by realcoloride** [comment]
Check out #180. I will get to it soon, I am currently busy working on another project.

**Comment by realcoloride** [comment]
Hey there, sorry for the lack of updates.

Could using the [livekit client](https://docs.livekit.io/client-sdk-js/) be a great idea to handle the actual TTS part? Also, upon investigating the way it authorizes access to the actual livekit session is weird.

**Comment by Jatinverma0786** [comment]
> Hey there, sorry for the lack of updates.
> 
> Could using the [livekit client](https://docs.livekit.io/client-sdk-js/) be a great idea to handle the actual TTS part? Also, upon investigating the way it authorizes access to the actual livekit session is weird.

As for my information it's not using livekit anymore they are using there own system as of now they are fetching Mp3 file from there server.

**Comment by realcoloride** [comment]
Hello. This is being worked on so all future discussion will be redirected here #180 
If you have any problems, feel free to re-open a new issue.
