### ISSUE TITLE
Timeout ms

### ISSUE THREAD

**Issue by Galang-Purnama** [realcoloride/node_characterai#173]
Why does a timeout appear? Even though usually the timeout doesn't appear. Has it been blocked by Cloudflare?
![Screenshot_20240528-220739_Termius](https://github.com/realcoloride/node_characterai/assets/133601562/b141d6fa-9a0e-46b7-8974-4c945ab6f935)

**Comment by realcoloride** [comment]
Hello, is your chromium browser up to date?

**Comment by Galang-Purnama** [comment]
> Hello, is your chromium browser up to date?

Yes, and of course.

**Comment by realcoloride** [comment]
Does this happen everytime you run the script?

**Comment by Galang-Purnama** [comment]
> Does this happen everytime you run the script?

Yes

**Comment by realcoloride** [comment]
Hey there, the chromium instance being opened might be the wrong one. 
Could you try doing `which chromium-browser` and send me the path?

**Comment by Galang-Purnama** [comment]
> Hey there, the chromium instance being opened might be the wrong one. Could you try doing `which chromium-browser` and send me the path?

Oh, it turns out the path was just wrong, thanks for the help

**Comment by Galang-Purnama** [comment]
> Hey there, the chromium instance being opened might be the wrong one. Could you try doing `which chromium-browser` and send me the path?

Oh, it turns out the path was just wrong, thanks for the help

**Comment by realcoloride** [comment]
No problem,  glad I could help.
Cheers
