### ISSUE TITLE
How do you install chromium?

### ISSUE THREAD

**Issue by jacpa2011** [realcoloride/node_characterai#176]
I know it's in README.md but this situation is more specific... it's a really strict Linux host server I'm trying to run in, I cannot run commands, only `npm install` but no specifications (like `npm install [modulename] -- [spefics]`) Are there any chromium files I can manually put in?

**Comment by realcoloride** [comment]
What distribution and version of it are you using? (e.g. Ubuntu 22.04) and
do you have the ability to do apt-get install?

**Comment by jacpa2011** [comment]
I don't know.. all I know is that it's Linux and that's it
also like I said, I can't do apt-get installs since the only command I can do is `npm install` (And also because there isn't any apt apparently)
It's using Pterodactyl though if that helps.
Maybe I could manually put in files? and then configure the path there.

**Comment by realcoloride** [comment]
I cannot help you without the information I asked for. Sorry.

**Comment by jacpa2011** [comment]
I got the distribution and version! It's Ubuntu 22.04, I hope this helps you now.

**Comment by realcoloride** [comment]
Could you run `$ which chromium-browser` and give me the output?

**Comment by jacpa2011** [comment]
..once again for the third time, I cannot do ANY commands besides `npm install`
also, I'm pretty sure it would throw an error anyway since it doesn't have chromium.. at all
And I cannot access any other files (example: os files [excluding cmd]) except my own files with or without `npm install`
I think the only solution would be to just manually put the files in (like I suggested multiple times)
