### ISSUE TITLE
need hep stuck with problem for 4 weeks 😭😭😭

### ISSUE THREAD

**Issue by heyeanne34** [realcoloride/node_characterai#177]
Can i ask what would be the full code to prompt character ai through command prompt by batch using their api? 🥺🥺 what i want is to ask a question to all characters i picked and all their responses (their names included in responses so i can track them) will be in a file saved in my folderpath ive been stuck with this for 4 weeks and never figured it out 😭😭😭

**Comment by realcoloride** [comment]
Hello,

I don't really understand what you're asking. Is this a problem related to the `node_characterai` package or not?

Cheers
