### ISSUE TITLE
Multiple conversation

### ISSUE THREAD

**Issue by Dimas-Saputra-Me** [realcoloride/node_characterai#178]
## Question
Is there any guide regarding on `🪐 How to use an account to mass use the library?` in the readme?

## What I have tried
I have tried to use some method like [this one](https://github.com/realcoloride/node_characterai/blob/65c345a0f9e452915701f02fc6835f3da60c4cf5/chat.js#L140) But it seems there is a specific variable type for the `conversationExternalId`
I have also tried to put `externalId` on [this method](https://github.com/realcoloride/node_characterai/blob/65c345a0f9e452915701f02fc6835f3da60c4cf5/client.js#L130). But I'm also getting an error to (might be a wrong type of externalId)

Thank you

**Comment by realcoloride** [comment]
Hello, the externalId concerns conversations on the OLD interface of CharacterAI. Consider using this: https://github.com/realcoloride/node_characterai/issues/157#issuecomment-2005709711

**Comment by Dimas-Saputra-Me** [comment]
Alright, thank you so much

**Comment by realcoloride** [comment]
No problem! Happy coding!

**Comment by realcoloride** [comment]
No problem and happy coding! Also, its worth noting you can create as much as Chat objects from the client as you wish for your conversations. Have a great day!
