### ISSUE TITLE
Can't read properties of undefined in sendAndAwaitResponse (used with authenticatewithToken)

### ISSUE THREAD

**Issue by Sitri2002** [realcoloride/node_characterai#18]
I'm on Node v18+, so there shouldn't be compatible issues I think.

**Comment by realcoloride** [comment]
see #17

**Comment by Debanjan-San** [comment]
same issue and authenticateAsGuest(); is also showing error

**Comment by realcoloride** [comment]
see #17

**Comment by realcoloride** [comment]
Fixed in https://github.com/realcoloride/node_characterai/issues/17
