### ISSUE TITLE
Erro 

### ISSUE THREAD

**Issue by klauskkj10** [realcoloride/node_characterai#181]
What do I do in this situation?![IMG_20240808_211431.jpg](https://github.com/user-attachments/assets/67f818ea-9767-4a26-b5ca-29f16e792f5f)

**Comment by realcoloride** [comment]
See https://github.com/realcoloride/node_characterai?tab=readme-ov-file#troubleshooting
![image](https://github.com/user-attachments/assets/15c8faea-5aef-48d8-8354-ba76e9799610)

**Comment by klauskkj10** [comment]
> See https://github.com/realcoloride/node_characterai?tab=readme-ov-file#troubleshooting
> ![image](https://github.com/user-attachments/assets/15c8faea-5aef-48d8-8354-ba76e9799610)
> 

![Screenshot_2024-08-08-21-36-27-385_com.android.chrome-edit.jpg](https://github.com/user-attachments/assets/0afc4da2-3383-4bbf-b516-a296e5c1b35d)

**Comment by realcoloride** [comment]
Hey there, any news?

**Comment by klauskkj10** [comment]
> Hey there, any news?

I gave up

**Comment by realcoloride** [comment]
Okay, sorry to hear! If you later need to, feel free to re-open this or a new issue in case you have problems.
