### ISSUE TITLE
Token Authentication Failure & Server Error 500

### ISSUE THREAD

**Issue by Topandhi** [realcoloride/node_characterai#183]
Description
When attempting to authenticate using a token, the server returns an "Invalid Token" error. I tried using Postman to check the issue further, but encountered a 500 Internal Server Error. It seems that something may have changed in how tokens are handled.

Steps to Reproduce

Authenticate with a token:
Receive "Token is invalid" error:
![TOKEN INVALID 1](https://github.com/user-attachments/assets/bbe0c7e5-95b7-45de-ad9a-e4498fd4789b)

Add log to request variable on client.js and got internal server error 500:
![LOG RESPONSE](https://github.com/user-attachments/assets/650650f6-42e2-4afc-93f9-1e528a74490d)

Use Postman to check the token:
![TOKEN INVALID 0](https://github.com/user-attachments/assets/1a266bef-2e4b-43b7-928a-b09aaaa8959d)
![TOKEN INVALID 4](https://github.com/user-attachments/assets/40ba9e35-aa5b-4849-9c56-3cf85d090c26)
![TOKEN INVALID 3](https://github.com/user-attachments/assets/5c742e8b-7320-4e47-8a4f-a680046b3e0d)
![TOKEN INVALID 2](https://github.com/user-attachments/assets/92461628-2209-4309-8c3c-77460921d48c)
Encounter 500 Internal Server Error:

Expected Behavior
The token should be validated correctly, and the server should not return a 500 Internal Server Error.

Additional Context
I suspect there may have been a recent change in how tokens are processed

**Comment by realcoloride** [comment]
Hello, what version of node_characterai are you using?

**Comment by Topandhi** [comment]
Thank you for the quick response! I was indeed using an outdated version of node_characterai (version 1.1.0). After updating to the latest version 1.2.7, the issue was resolved, and everything is working fine now. Thanks again for your help!

**Comment by realcoloride** [comment]
No problem. Feel free to open a new issue if you have a new problem or suggestions. Happy coding!
