### ISSUE TITLE
Error Locating Chromium

### ISSUE THREAD

**Issue by Vernityz** [realcoloride/node_characterai#184]
![Screenshot_2024-09-22-09-13-33-105_com android chrome](https://github.com/user-attachments/assets/1c2d394b-864b-48d0-9e6c-78938e064dfb)

i checked the chromium path is fine, but how can this error is occurred?
i use pterodactyl

**Comment by realcoloride** [comment]
This is the puppeteer cache, try installing the chromium browser directly instead and locate it. See: https://github.com/realcoloride/node_characterai?tab=readme-ov-file#specifying-chromiums-path

**Comment by Vernityz** [comment]
ahh, thankyou, should work now
