### ISSUE TITLE
Question, can i authenticate the api in one file and send a message in another?

### ISSUE THREAD

**Issue by thatlittledrummerboi** [realcoloride/node_characterai#186]
i'm building a discord bot and i want to make an event for the discord bot to call `authenticateWithToken()` in a file "initCAI.js"

then, in another file "allowedChannelMessage.js" i want to use an event `messageCreate` to use the already authenticated process to send a mesasage that way, to lower response time.

screenshot of initCAI.js 
![image](https://github.com/user-attachments/assets/c10531a9-4cd8-4059-8761-9c382bf4b413)

**Comment by realcoloride** [comment]
Hello there, I am not quite sure to understand what you are asking.
Are you trying to authenticate when the bot is ready? Or emit an event when the characterAI instance is ready?

Also, if this is not an issue related to the package itself, I recommend you close the issue (it will not be locked however and you can keep interact with it).

Cheers

**Comment by thatlittledrummerboi** [comment]
nevermind lol, I basically just answered my own question.. sry bout that!
