### ISSUE TITLE
old.character.ai redirects

### ISSUE THREAD

**Issue by jacpa2011** [realcoloride/node_characterai#187]
Please change the tutorial for mobile as old.character.ai now redirects you to the new site.

**Comment by jacpa2011** [comment]
ah it seems it was already resolved in another issue, however you should change the README.md.

**Comment by realcoloride** [comment]
Hello, you're right, but I need to specify I'm working on 2.0, and in that current moment I do not currently support a way or have looked for to gather the authorization token for mobile. However, I will have updated documentation in 2.0 and I'd rather write something that is comprehensive and good for release. 

In the meantime, you can check the following comment to temporarily get your token: https://github.com/realcoloride/node_characterai/issues/146#issuecomment-2440173757
For the 2.0 roadmap, see #180 

Cheers
