### ISSUE TITLE
500 internal server error

### ISSUE THREAD

**Issue by Topandhi** [realcoloride/node_characterai#188]
![Screenshot_20241118-200517](https://github.com/user-attachments/assets/aa7d315a-fc4a-4be5-ab64-43460efbef3d)

got response 500 internal server error on function
 sendAndAwaitResponse in file chat.js

**Comment by IceVladimir** [comment]
same error

**Comment by realcoloride** [comment]
Hello

![image](https://github.com/user-attachments/assets/a1052402-35e1-449e-809e-74d4bea8b6da)
The error is listed right here: the message was flagged.

**Comment by Topandhi** [comment]
i dont think so, it got block even with new session.

but as today its work fine again,
i will close this issue
