### ISSUE TITLE
Any way to retrieve the voice message from the character.ai response?

### ISSUE THREAD

**Issue by chimaerra** [realcoloride/node_characterai#189]
I mean this in the character.ai text, just above the text bubble there's a button to play audio with the voice of the picked character. On click there's an event in the network tab (replay) "/multimodal/api/v1/memo/replay", in the response itself there's a link to a temporarily stored mp3 file with some kind of tokenization "https://storage.googleapis.com/character-ai-multimodal-memo/voice_generated/". I tried to look up similar issues but I've only found the references of a call, not text-driven audio response.
![66](https://github.com/user-attachments/assets/d26eab0b-f46a-4426-9afb-00124233f77e)

**Comment by realcoloride** [comment]
Hello, this is a feature that has been implemented in the 2.0 branch, but it is currently in work.

https://github.com/realcoloride/node_characterai/issues/180
https://github.com/realcoloride/node_characterai/blob/2.0/src/chat/message.ts#L301

**Comment by chimaerra** [comment]
Oh well, I unfortunately have no clue how to work with typescript by any means, so I guess I'll wait for a release of it, thanks.

**Comment by realcoloride** [comment]
At the moment I'm working intensively on it, but I appreciate your patience.
In the mean time, here is how you can do it yourself:
https://github.com/realcoloride/node_characterai/blob/2.0/src/chat/candidate.ts#L114

The endpoint is `https://neo.character.ai/multimodal/api/v1/memo/replay`, `POST` request,
make sure to include the following in your body:

```typescript

            body: Parser.stringify({ 
                candidateId: this.candidateId,
                roomId: this.message.chatId,
                turnId: this.message.turnId,
                voiceId,
                voiceQuery
            }),
```

Hope this helps you out.

Cheers
