### ISSUE TITLE
How to receive data as a stream?

### ISSUE THREAD

**Issue by alexying1** [realcoloride/node_characterai#24]
Hello. This project helps me a lot. However there is still a problem for me. When I call sendAndAwaitResponse. It seems that I have to wait until all the reply text generated. Is there any way to read the data little by little instead of reading all the response data?

**Comment by realcoloride** [comment]
Glad to know it helps you in some way!

Sadly no due to how fetching works currently as we evaluate the puppeteer browser response beforehand. If cloudflare wasnt a thing there might have been a way.

I hope this answer helps and correct me if I'm wrong.
