### ISSUE TITLE
Error: Failed to launch the browser process puppeteer

### ISSUE THREAD

**Issue by iblmln** [realcoloride/node_characterai#25]
I have an error here.

**Information**
ECMAScript: 6
Hosting: Repl.it

**Comment by iblmln** [comment]
I'm building a WhatsApp Bot using @adiwajshing/baileys.

```javascript
// ai.js

import CharacterAI from 'node_characterai';
const characterAI = new CharacterAI();

export default async function({bot, command_name, input, message, prefix}) {
  if (!input) return message.reply(`*ChatGPT*\nMengobrol dengan AI.\n\nPenggunaan: ${prefix + command_name} <text>\nContoh: ${prefix + command_name} Apa itu AI?\n\nCatatan: ChatGPT ini dari character.ai, bukan ChatGPT asli tapi clone yang menurut saya bisa menggantikannya.`);
  
  (async() => {
      await characterAI.authenticateWithToken('token'); // I already have the access token, removed due to privacy issues
      
      const characterId = "8_1NyR8w1dOXmI1uWaieQcd147hecbdIK7CeEAIrdJw" // ChatGPT
      const chat = await characterAI.createOrContinueChat(characterId);
      const response = await chat.sendAndAwaitResponse(input, true)
      message.reply(response);
    })();
}
```

**Comment by realcoloride** [comment]
Hello! I do not use replit sadly so I will mention this issue in #17 as a note. Users have been able to use it on Heroku or local.
What version of the package do you use?

**Comment by Naozumi520** [comment]
Any more info? Like chromium not found or what?

**Comment by iblmln** [comment]
> Any more info? Like chromium not found or what?

Nothing else, just announced that the browser failed to launch

**Comment by iblmln** [comment]
> Hello! I do not use replit sadly so I will mention this issue in #17 as a note. Users have been able to use it on Heroku or local. What version of the package do you use?

It turned out that after I searched, Puppeteer really didn't work on Replit, I was disappointed with this. Hope this is fixed soon.

**Comment by JcynR** [comment]
I have the same problem, on windows...

```
node_modules\@puppeteer\browsers\lib\cjs\launch.js:262

                reject(new Error([
                       ^

Error: Failed to launch the browser process!


TROUBLESHOOTING: https://pptr.dev/troubleshooting
```

**Comment by realcoloride** [comment]
try unistalling and reinstalling the puppeteer package

**Comment by Jeffgrey91** [comment]
@realcoloride The issue is still there.

**Comment by realcoloride** [comment]
Hello again, whats the problem exactly?
