### ISSUE TITLE
Error: Failed to fetch | TypeError: Cannot read properties of undefined (reading 'status')

### ISSUE THREAD

**Issue by Mariotim3** [realcoloride/node_characterai#26]

**Comment by realcoloride** [comment]
Hello!

Could you specify more details about what happened? Code, error path, etc...

**Comment by Mariotim3** [comment]
I believe it's due to attempting to send multiple messages while one is already being generated. I have resolved the issue by waiting until one is completed before sending the next one. Will let you know if I find more issues. Thanks for making this

**Comment by Mariotim3** [comment]
I decided to use multiple instances of the node_characterai and run them separately. So that if the bot is already generating a message for one response it can use the other instances to generate one for another. (It seems to have worked and now has the ability to generate multiple responses at the same time.)

I have only had the issue once since then, and i'm still trying to find more info about it.

The issue also seems to occur under the chat.js file, on line 65.

` if (request.status() === 200) {
TypeError: Cannot read properties of undefined (reading 'status')`

**Comment by realcoloride** [comment]
If request is undefined it means something went wrong with the puppeteer evaluation, as it returns an object and the status is a procedurally generated function when /streaming/ is called.

**Comment by cshadd** [comment]
I can confirm the same thing happening on my end. I have not tried the similar fix of multiple instances of node_characterai.

I can confirm this happens if multiple fetches are happening at the same time.

**Comment by Mariotim3** [comment]
I did try queueing each one and waiting for it to finish and it did work. Although if I had multiple users conversing with it at the same time the chat would end up getting really far behind (because it takes anywhere from around 4 - 10 seconds to generate a response) and was not able to respond to new ones quick enough.

**Comment by cshadd** [comment]
One other solution I can think of at this moment is to try multiple puppeteer instances per request call without having to force the develop to make a new client. This still will make a chromium instance and multiple puppeteer instances for all the requests but this is probably better for the end developer.

**Comment by creepycats** [comment]
`node_characterai` I believe has the same issue that I had before with multiple messages sending. 

I don't know exactly how `requester.js` works just yet, but just a suggestion for coloride.

Add some sort of "request_id" header to requests. I use this to make sure whatever I request is what I intercept.

This basically fixes issues with Eval-Fetching and makes sure we only listen to requests we want.

![image](https://github.com/realcoloride/node_characterai/assets/68137105/a761974b-1885-4e1f-a357-7b4b77d7155c)
![image](https://github.com/realcoloride/node_characterai/assets/68137105/44dbd75a-78b4-4d60-96b3-59c19c998c5a)
![image](https://github.com/realcoloride/node_characterai/assets/68137105/3cf5e178-2f1f-45ec-8e5f-47b4a0ec85aa)

Of course, I don't know what might break with this change. Could be set up like this for a very specific reason. This would just let you use one singular type of requesting that should hopefully fix whatever issue this is.

**Comment by Parking-Master** [comment]
You can close this issue now. It was definitely related to a caching problem and has been resolved now as of v1.8.8.
