### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by bwkam** [realcoloride/node_characterai#29]
So I just tried copying the example snippet in the README and running that, but it logs two messages and then stops, and doesn't print the response 
![image](https://user-images.githubusercontent.com/91009118/232250438-4a75b37e-bf7d-4886-9a05-6cc8a1f9ae6f.png)

**Comment by bwkam** [comment]
I suspect it's an issue with `initialize` in requester.js, and any code after `authenticateAsGuest` doesn't run, but not sure where's the issue here.

**Comment by Skekdog** [comment]
When authenticating with token, initlialize succeeds, however it stops at
![image](https://user-images.githubusercontent.com/47750815/232251970-54f71fea-8773-4a1b-8822-2aabd287c926.png)
beta.character.ai claims to be down right now, however this also occurred prior
Trying to access from browser put me on a cloudflare waitlist (prior to being down), not sure if that has anything to do with it

**Comment by bwkam** [comment]
yeah the issue was from CAI's side, it's working now, thanks.
