### ISSUE TITLE
Cannot read properties of undefined (reading 'find')

### ISSUE THREAD

**Issue by zyxFront** [realcoloride/node_characterai#3]
client.js(154)  const continueBody = response;  
the response is string type, should be parsed.

 const continueBody = JSON.parse(response);

**Comment by realcoloride** [comment]
Hello and thanks for the bug report. I am aware of it.

I update everything in the issue #2.
Expect a bugfix update today.

**Comment by realcoloride** [comment]
https://github.com/realcoloride/node_characterai/issues/2#issuecomment-1439969007

Hello, this issue has been resolved!
Please open a new issue if you have to report any other bugfix.

Have fun!
