### ISSUE TITLE
Hanging on characterAI.authenticateAsGuest

### ISSUE THREAD

**Issue by BrettPatterson1** [realcoloride/node_characterai#30]
When I try calling await characterAI.authenticateAsGuest it hangs sometimes. Is this due to the cloudflare protection on the website? When I add logs inbetween that await call it doesn't get past that line. 

I get the console logs 
[node_characterai] Puppeteer - This is an experimental feature. Please report any issues on github.
[node_characterai] Puppeteer - Done with setup
but nothing afterwards.

**Comment by realcoloride** [comment]
Yes its cloudflare's dumb shit with waiting times that might be yielding it, sorry!

**Comment by BrettPatterson1** [comment]
Damn that's too bad.

**Comment by BrettPatterson1** [comment]
Do you know if its possible to wait until the cloudflare protection has passed? Once it starts hanging it doesn't stop and I'm wondering if I can just increase the timeout or something. Still a noob here though so I'm not sure lol.

**Comment by realcoloride** [comment]
No because its unpredictable sadly

**Comment by realcoloride** [comment]
```js
[node_characterai] Puppeteer - ProtocolError: Page.navigate timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.
client.js:211
        if (request.status() === 200) {      
                    ^

TypeError: Cannot read properties of undefined (reading 'status')
    at Client.authenticateAsGuest (client.js:211:21)

**Comment by realcoloride** [comment]
Hello, it seems its coming from the change of going via the new headless mode.

**Comment by realcoloride** [comment]
Hello, upon testing, the issue seems like its coming from a new slowdown of the new headless mode. Trying in old `true` headless mode seems to be working perfectly.

**Comment by realcoloride** [comment]
For some reason it feels like I cant even run it properly anymore.. I need to probably investigate deeper on this issue.

**Comment by realcoloride** [comment]
Why is the page timing out? Is it cloudflare doing something?

**Comment by realcoloride** [comment]
So sometimes it seems to work properly and sometimes it just hands on "https://beta.character.ai/chat/auth/lazy/". Running it on headful right now and I think they're now either waiting for you to click on the Accept cookie button, or they have a rate limit, or more, user input

**Comment by realcoloride** [comment]
Ok, after investigation, it might be an issue with CORS policies either from puppeteer or stealth plugin.

![chrome_4bMKiQ99Vk](https://github.com/realcoloride/node_characterai/assets/108619637/183ac379-f9c1-489e-8aad-5be1f02f6782)

**Comment by realcoloride** [comment]
Ok so I have made an experimental thing that keeps trying to generate a session for atleast 20 times until a response is recieved because I suspect there is now something around uuids.
![Code_6Oq2oVYaP8](https://github.com/realcoloride/node_characterai/assets/108619637/b07f36f5-d1a7-4b7a-ba60-169316d9b2fb)

**Comment by realcoloride** [comment]
Problem seems to have been fixed with this solution. If any have any errors or feedback, let me know. Commits:  https://github.com/realcoloride/node_characterai/commit/d1b62727591943833ef9e255353568d02d3e3f1f and https://github.com/realcoloride/node_characterai/commit/25a541d287f53e23443d9f80f3e3e0ead5ffefd8
