### ISSUE TITLE
How to let it work on Linux?

### ISSUE THREAD

**Issue by alexying1** [realcoloride/node_characterai#31]
Hello. Does this project support Linux?

**Comment by realcoloride** [comment]
Probably, I am unsure as I have not tested (I don't have Linux)

**Comment by cshadd** [comment]
Can confirm this works on Red Hat Linux Server.

**Comment by MustafaBaypara** [comment]
its ok with ubuntu 22.10

**Comment by realcoloride** [comment]
Thank you for the information. To OP or future posters, please re-open a new issue if you need to talk about the topic or a related issue.
