### ISSUE TITLE
Adding image support

### ISSUE THREAD

**Issue by onnowhere** [realcoloride/node_characterai#33]
Some of the characters generate images alongside text, thought it might be a good idea to include the image as well in the response.

Example character: https://beta.character.ai/chat?char=bQBlcCVVjfTAzv8OWK30dw7Tj-TNtKC_Rh0Z46Dx6fY

Small change can be added to include this in `message.js` for the `Reply` class by reading `replyOptions.image_rel_path`. Side note, I have noticed that the link itself doesn't generate an image immediately upon the url being returned in the response (gives a 404 if too soon), but usually needs a moment of wait before it's ready.

Also, may take a bit more work but these image path may be of interest for uploading images to be referenced in the chat as well:
- `beta.character.ai/chat/upload-image/`
    - Request: `image: (binary)`
    - Response: `{status: "...", value: "..."}`
- `beta.character.ai/chat/generate-image/`
    - Request: `{image_prompt_text: "..."}`
    - Response: `{image_rel_path: "..."}`
    
Message request also seems to have these fields now relating to images:
- image_description: ""
- image_description_type: "AUTO_IMAGE_CAPTIONING" (example)
- image_origin_type: "UPLOADED"  (example)
- image_rel_path: "..."
- REMOVED image_prompt_text

**Comment by realcoloride** [comment]
Hello! This seems like a good idea.
If you can create a pull request and able to give changes in that usage, please let me know!

**Comment by creepycats** [comment]
Been working on my own alternative single-file CharacterAI Headless thing because this one has been a little wonky. Works great but I still gotta deal with the Waiting Room breaking it sometimes.

Friends told me to add Image support. AFAIK I could only get `image_rel_path` to load images uploaded to C.AI, otherwise it sent errors back.

So I got to work and made a Fetch Request for Uploading images from a different url to get a Character.AI image url.

IDK if this is useful or what but here:
```js
let imgUrl = "https://i.natgeofe.com/n/548467d8-c5f1-4551-9f58-6817a8d2c45e/NationalGeographic_2572187_square.jpg"
fetch(imgUrl)
    .then(res => res.blob())
    .then(async function(blob) {
        let file = new File([blob], "image");
        let fd = new FormData();
        fd.append("image", file);
        fetch("https://beta.character.ai/chat/upload-image/", {
                method: 'POST',
                headers: {
                    'Accept': 'application/json, text/plain, */*',
                    authorization: `Token ${token}`
                },
                body: fd
            })
            .then(function(response) {
                return response.json();
            }).then(function(data) {
                console.log(data); // {status: 'OK', value: 'uploaded/2023/5/5/D6RwZ4s0WffWqYMUN0PNxziLb7RlUh9z80P9qMhCO7A.webp'}
            });
    })

**Comment by realcoloride** [comment]
Hello! This is awesome!!!!

If you're able to make a pull request after testing and experimenting, i could combine them and push.

**Comment by creepycats** [comment]
I would but uh, CloudFlare waiting queue haha funny break my code. (Fetch request returns the html for the site instead of the endpoint shit super annoying)
![image](https://user-images.githubusercontent.com/68137105/236633625-bce6f01e-5065-4280-abaf-38e7ba78f53a.png)

Code shouldn't take too long but yeah the queue really annoys me. If you find/found a fix for the cloudflare thing please let me know.

**Comment by realcoloride** [comment]
you can do a try catch to avoid errors

**Comment by creepycats** [comment]
Ight.

Also just another thing i worked on whilst bored in class, fetch code for the Image Generation..

`${token}` is CAI account token
`${description}`is the image description
```js
fetch("https://beta.character.ai/chat/generate-image/",{
    headers:{
        Authorization: "Token ${token}",
        "Content-Type": "application/json"
    },
    method:"POST",
    body:JSON.stringify({
        image_description:${description}
    })
}).then(resp=>{return resp.json()}).then(response=>{
    console.log(response.image_rel_path);
})
```

**Comment by creepycats** [comment]
Another update:
I cannot seem to get even the base node_characterai package to authenticate. Console logging just shows me that it never reaches `networkidle2` in the `requester.js` call in the auth thing. 

I can't really tell why, and I don't feel like replacing the requester but Ill just do it anyways and tell you how that goes.

**Comment by creepycats** [comment]
Finishing up...

Basically added a special request `requester.js` for uploading the images without NodeJS being finnicky.

Two new `chat.js` functions for image generation and uploading, and I made sure you can use `sendAndAwaitResponse` as seen below.
```js
await chat.generateImage("dolphins swimming in green water")
// returns: URL as string

await chat.uploadImageFromLink("https://i.natgeofe.com/n/548467d8-c5f1-4551-9f58-6817a8d2c45e/NationalGeographic_2572187_2x3.jpg")
// returns: URL as string

await chat.sendAndAwaitResponse({text:"Whats this image?",image_rel_path:${imageUrl}}, true)
// replace imageUrl with one of the two urls obtained above and the character will recognize the image
```
I'll create the pull-request soon...

**Comment by creepycats** [comment]
[Speaking of...](https://github.com/realcoloride/node_characterai/pull/38)

**Comment by realcoloride** [comment]
Hello! I'll check it out as soon as I get home. 
See you soon!

**Comment by realcoloride** [comment]
Was pushed and added, see #17 for roadmap.
