### ISSUE TITLE
Does this in any way violate Character.ai ToS?

### ISSUE THREAD

**Issue by DefaltZ** [realcoloride/node_characterai#35]
I wish to use this package for a public discord bot project, so i would really like to know if using this package is permitted since i wish to keep the bot project legally safe in the long run.

**Comment by JcynR** [comment]
Yes it is against C.ai's TOS but violating it isn't illegal.

**Comment by justkorudev** [comment]
> 

It doesn't break the ToS, they say nothing about using APIs(to my knowledge)

**Comment by realcoloride** [comment]
Side-Comment:

This is not a rip of the API or any leak or anything related, everything that the API does by itself is able to be done by going on the website and using it or via your browser in any case.
This is just a wrapper for what you can do with the API.
