### ISSUE TITLE
Its load?

### ISSUE THREAD

**Issue by ThisMe124** [realcoloride/node_characterai#36]
I got this response in the console but not with the response text

![Screenshot_20230507-110033](https://user-images.githubusercontent.com/88891071/236655505-d089d002-491c-4033-b007-755fa49e34c0.jpg)

**Comment by Grammf** [comment]
It is. Try this one, it's more clear.
`const CharacterAI = require('node_characterai');
const readline = require("readline");
const characterAI = new CharacterAI();

const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
});

(async () => {
    await characterAI.authenticateWithToken("your_token");

    const characterId = "your_char_id"
    console.log("Creating a chat...")
    const chat = await characterAI.createOrContinueChat(characterId);
    console.log("Created!")
    process.openStdin();
    rl.on('line', async function (line) {
        if (line.startsWith("delmsg")) {
            console.log("Wait a little pls...")
            await chat.deleteMessagesBulk(Number(line.substring(line.indexOf(" ") + 1)), false)
            console.log("Deleted! \n")
        } else {
            const response = await chat.sendAndAwaitResponse(line, false)
            console.log(response)
        }
    })
})();`

**Comment by realcoloride** [comment]
Hello!
Is CharacterAI banned in your country? (I assume Russia) or were you in cloudflare time out when it happened?
Also, make sure your token and character id are valid.

**Comment by ThisMe124** [comment]
> Hello! Is CharacterAI banned in your country? (I assume Russia) or were you in cloudflare time out (see #39) when it happened? Also, make sure your token and character id are valid.

No i am from Indonesian

**Comment by ThisMe124** [comment]
actually it's been fixed. but can it be multi-response? in one command but using it more than one

**Comment by ThisMe124** [comment]
I tried Request 2 at the same time there was an error requests.

**Comment by realcoloride** [comment]
Issue has been resolved. See Issue #30 and #17 for a roadmap.
