### ISSUE TITLE
Expiration Dates

### ISSUE THREAD

**Issue by MaitreGEEK** [realcoloride/node_characterai#42]
Hey ! Do you happen to know if there's something that could be done to automatically create a token instead of recreating one at expiration dates ?

**Comment by realcoloride** [comment]
This is not a problem with the package but rather with the website

**Comment by MaitreGEEK** [comment]
And do you know if it's possible to create a method that with email and mdp or something like that login into the website and then get the acceskey automatically ?

**Comment by realcoloride** [comment]
You could probably automate the process yourself but it could take a while

**Comment by MaitreGEEK** [comment]
I see, if ever you add i'll look into it if I m really motivated xd
