### ISSUE TITLE
Removing pupeeter logs

### ISSUE THREAD

**Issue by MaitreGEEK** [realcoloride/node_characterai#43]
Can we remove this ? 

![image](https://github.com/realcoloride/node_characterai/assets/90345438/edcbedd4-7908-42c9-9454-9d55d79d39b7)

**Comment by realcoloride** [comment]
As of when the version was published new headless wasn't stable yet
Inside of requester.js, set the headless mode to 'new' instead of true.

However, if using 'new' is stable, it should be pushed next update.
