### ISSUE TITLE
response?

### ISSUE THREAD

**Issue by megaprinny** [realcoloride/node_characterai#44]
I am trying to return the response from the ai to use in my python environment, however no matter what I try it only returns this: 
![image](https://github.com/realcoloride/node_characterai/assets/65448117/d13562d2-72c5-4bd0-855e-0ab94afd4ba1)
I can see the ai responding in the java terminal and in the website though. here are my codes: 
![image](https://github.com/realcoloride/node_characterai/assets/65448117/c1df1c1d-ea02-449f-af2e-97b88e143a57)
![image](https://github.com/realcoloride/node_characterai/assets/65448117/44941176-37ef-4d91-b935-f8ec2faf69fb)

**Comment by realcoloride** [comment]
you're aware that response is the Reply class correct?

**Comment by megaprinny** [comment]
now I do, but I'm still a beginner. I was stuck because the response wouldn't show up in my python environment unless I killed the process. It's a different project so I shouldn't have asked, but I fixed it for myself by turning it into a function and then writing a file for the response
![image](https://github.com/realcoloride/node_characterai/assets/65448117/4854d3cb-1120-4519-8333-94dc9889e879)

**Comment by megaprinny** [comment]
I tried before that but it didn't work! actually my issue is resolved now! the code i posted was the solution that worked, so this thread can be closed now. my intent was to pass the response into a python code, sorry

**Comment by realcoloride** [comment]
ok all good have a nice day!
