### ISSUE TITLE
.createOrContinueChat hangs

### ISSUE THREAD

**Issue by BasicVariable** [realcoloride/node_characterai#47]
`requester.js:146[node_characterai] Puppeteer - ProtocolError: Page.navigate timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.`
`Uncaught TypeError: Cannot read properties of undefined (reading 'status')`

I'm authenticating with an ai+ token and it can authenticate the token, this is the code I'm trying to run:

```
const currentChat = new Promise(async (res, err) => {
    await character.authenticateWithToken(global.config.charAiToken);
    let chat = await character.createOrContinueChat("8_1NyR8w1dOXmI1uWaieQcd147hecbdIK7CeEAIrdJw")
    res (chat)
});

**Comment by realcoloride** [comment]
i dont think we support ai+ if it redirects to another domain

**Comment by realcoloride** [comment]
Added cai+ support (commit: https://github.com/realcoloride/node_characterai/commit/48ab38171201650af5dcd1043da8bfce163dc43e).
#17 to see the current roadmap.
