### ISSUE TITLE
fetchHistory() is broken in npm version

### ISSUE THREAD

**Issue by Shiro-Nek0** [realcoloride/node_characterai#5]
npm version has '  instead of `, and that causes history to not work

![image](https://user-images.githubusercontent.com/30852897/220809953-87be93f5-7663-41d4-a9ba-0222661ba77a.png)

![image](https://user-images.githubusercontent.com/30852897/220810950-4e1f65ba-851d-4fd7-8e62-a039395b16f6.png)

**Comment by realcoloride** [comment]
Hello!

Thanks for letting me know.
I will fix those issues today.

If you have anything else to report or have questions please let me know.

Have fun!

Le jeu. 23 févr. 2023 à 03:54, ShiroNeko ***@***.***> a
écrit :
