### ISSUE TITLE
Often crashes while using as a Discord bot...

### ISSUE THREAD

**Issue by Arusu12** [realcoloride/node_characterai#52]
I tried making a Discord Bot using this package and I have discovered that it often crashes and I can't find a reason why. Can't navigate to the chat.js file.

The error is the the following-
```
node:events:491
      throw er; // Unhandled 'error' event

TypeError: Cannot read properties of undefined (reading 'length')
    at Chat.sendAndAwaitResponse (D:\node_modules\node_characterai\chat.js:71:41) 
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Client.<anonymous> (D:\index.js:39:26)
Emitted 'error' event on Client instance at:
    at emitUnhandledRejectionOrErr (node:events:394:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)

Node.js v18.14.0
```

My code is the following-
```
const { Client, GatewayIntentBits} = require('discord.js');
let client = new Client({
    intents: [
        GatewayIntentBits.Guilds,
		GatewayIntentBits.MessageContent,
        GatewayIntentBits.GuildMembers,
        GatewayIntentBits.GuildMessages,
        GatewayIntentBits.GuildVoiceStates,
        GatewayIntentBits.GuildEmojisAndStickers,
        GatewayIntentBits.GuildIntegrations,
        GatewayIntentBits.GuildInvites,
        GatewayIntentBits.GuildMessageReactions,
        GatewayIntentBits.GuildMessageTyping,
        GatewayIntentBits.GuildWebhooks,
    ],
    disableMentions: 'everyone',
});

client.on('ready', () => {
    console.log(`Logged in as ${client.user.tag}!`);
  });

const CharacterAI = require('node_characterai');
const characterAI = new CharacterAI();

(async() => {
    await characterAI.authenticateAsGuest();

    const characterId = "CHARACTERID"

    const chat = await characterAI.createOrContinueChat(characterId);

    client.on('messageCreate', async message => {
        if (message.author.bot || !message.content) return;
        message.channel.sendTyping();

        const prompt = message.content
      
        const response = await chat.sendAndAwaitResponse(prompt, true);
        message.channel.send(response.text);
      });

})();

client.login('TOKEN');
```
I hope for a solution :) . And thanks for making this package.

**Comment by Arusu12** [comment]
Wait, just wondering... Is it because of the Guest mode?

**Comment by realcoloride** [comment]
Hello, can you tell me what is in
    at Chat.sendAndAwaitResponse (D:\node_modules\node_characterai\chat.js:71:41)

**Comment by Hexioum** [comment]
I have the exact same problem. Authenticating with token.

This is in chat.js:71:41
`for (let i = 0; i < replies.length; i++) {`

When attaching the debugger it says that the response was 'Server Error (500)'

**Comment by Arusu12** [comment]
I have tried direct redirect to the code (using VS Code) but it didn't seem to work. Will let you know after checking it out.

**Comment by Arusu12** [comment]
Yep, as @Hexioum said, the code in chat.js:71:41 is-
```
for (let i = 0; i < replies.length; i++) {
                messages.push(new Reply(this, response));
            }
```
Just to let you know, the error happened to me when I tried using authenticate as Guest. It didn't occur ever since I changed to token method.

**Comment by realcoloride** [comment]
Ok, from inspecting it means that fetching the reply failed and since there was no try catch, it errored and stuck your code.

For now you should try catch to avoid making your discord bot. Sorry for the incovenience.

**Comment by Parking-Master** [comment]
`replies' is clearly undefined. Hence the error - "cannot read property "length" of undefined". What is happening here is the code is running, expecting the AI to generate a response, but runs anyway even know it hasn't responded yet. So here is what I think happened:

- You're sending too many messages and the AI stops (because of using guest authentication)
- The `for` loop must wait until the AI generates a full response (with Promises/await)

**Comment by Parking-Master** [comment]
This issue seems to already be fixed though :)

So this issue can be closed
