### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by ClayzaAubert** [realcoloride/node_characterai#53]
I use this code for discord bot, and I run it on local successfully, but I try to run it on replit and my Vps there is an error like this, is there a solution?

```
[node_characterai] Puppeteer - This is an experimental feature. Please report any issues on github.

  Puppeteer old Headless deprecation warning:
    In the near feature `headless: true` will default to the new Headless mode
    for Chrome instead of the old Headless implementation. For more
    information, please see https://developer.chrome.com/articles/new-headless/.
    Consider opting in early by passing `headless: "new"` to `puppeteer.launch()`
    If you encounter any bugs, please report them to https://github.com/puppeteer/puppeteer/issues/new/choose.

/home/runner/ru-chan/node_modules/puppeteer/node_modules/@puppeteer/browsers/lib/cjs/launch.js:259
                reject(new Error([
                       ^

Error: Failed to launch the browser process!
/home/runner/.cache/puppeteer/chrome/linux-113.0.5672.63/chrome-linux64/chrome: error while loading shared libraries: libgobject-2.0.so.0: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://pptr.dev/troubleshooting

    at Interface.onClose (/home/runner/ru-chan/node_modules/puppeteer/node_modules/@puppeteer/browsers/lib/cjs/launch.js:259:24)
    at Interface.emit (node:events:525:35)
    at Interface.emit (node:domain:489:12)
    at Interface.close (node:internal/readline/interface:536:10)
    at Socket.onend (node:internal/readline/interface:262:10)
    at Socket.emit (node:events:525:35)
    at Socket.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
```

**Comment by realcoloride** [comment]
Hello,

Since this is an issue relating to linux (which I don't have or have much experience with) or puppeteer, I cannot really help you there sadly.
However, you should probably try to look out for solutions directly online or if any contributor wants to help you there.

**Comment by Parking-Master** [comment]
I am getting this same exact message, see #50

**Comment by Arusu12** [comment]
This is most likely an issue with Puppeteer working on linux. Check the Puppeteer github. I remember them mentioning that if you are hosting the server on something like render, replit or heroku, you need to change the chromium installation location.
But this modification maybe needs to be made inside `node_characterai`'s code?

**Comment by realcoloride** [comment]
https://github.com/realcoloride/node_characterai/commit/06aca019527ee81492fe746f70120133a3f51424

Here is a commit.
Now, you should do
CharacterAI() -> characterAI.requester.puppeterPath

**Comment by Parking-Master** [comment]
@realcoloride got it working like a breeze on my Mac. Guess it just doesn't work on linux. It's still okay, I can use it on my Mac just fine

**Comment by realcoloride** [comment]
Good to know!

**Comment by Parking-Master** [comment]
@realcoloride on #17, I found a solution all the way at the bottom where a user got puppeteer working on the raspberry pi 4b, exact problem as me. I’m going to try it tomorrow and see if it works. Thanks for your help and amazing repository! 🙂

**Comment by Parking-Master** [comment]
@realcoloride oh wow, I got it working on linux! One little line of code fixed it. Thanks!

**Comment by Parking-Master** [comment]
Just go to `~/node_modules/node_characterai/requester.js` and on line 39, you'll see this:
```javascript
        const browser = await puppeteer.launch({
            headless: this.#headless,
            args: [
                '--fast-start',
                '--disable-extensions',
                '--no-sandbox',
                '--disable-setuid-sandbox',
                '--no-gpu',
                '--disable-background-timer-throttling',
                '--disable-renderer-backgrounding',
                '--override-plugin-power-saver-for-testing=never',
                '--disable-extensions-http-throttling',
                '--user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.3'
            ]
        });
        this.browser = browser;
```

Add this to line 39:
```javascript
executablePath: "/usr/bin/chromium-browser"
```

And now it should look like this:
```javascript
        const browser = await puppeteer.launch({
            headless: this.#headless,
            args: [
                '--fast-start',
                '--disable-extensions',
                '--no-sandbox',
                '--disable-setuid-sandbox',
                '--no-gpu',
                '--disable-background-timer-throttling',
                '--disable-renderer-backgrounding',
                '--override-plugin-power-saver-for-testing=never',
                '--disable-extensions-http-throttling',
                '--user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.3'
            ],
            executablePath: "/usr/bin/chromium-browser",
        });
        this.browser = browser;
```

**Comment by zyx-24** [comment]
> Just go to `~/node_modules/node_characterai/requester.js` and on line 39, you'll see this:
> 
> ```js
>         const browser = await puppeteer.launch({
>             headless: this.#headless,
>             args: [
>                 '--fast-start',
>                 '--disable-extensions',
>                 '--no-sandbox',
>                 '--disable-setuid-sandbox',
>                 '--no-gpu',
>                 '--disable-background-timer-throttling',
>                 '--disable-renderer-backgrounding',
>                 '--override-plugin-power-saver-for-testing=never',
>                 '--disable-extensions-http-throttling',
>                 '--user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.3'
>             ]
>         });
>         this.browser = browser;
> ```
> 
> Add this to line 39:
> 
> ```js
> executablePath: "/usr/bin/chromium-browser"
> ```
> 
> And now it should look like this:
> 
> ```js
>         const browser = await puppeteer.launch({
>             headless: this.#headless,
>             args: [
>                 '--fast-start',
>                 '--disable-extensions',
>                 '--no-sandbox',
>                 '--disable-setuid-sandbox',
>                 '--no-gpu',
>                 '--disable-background-timer-throttling',
>                 '--disable-renderer-backgrounding',
>                 '--override-plugin-power-saver-for-testing=never',
>                 '--disable-extensions-http-throttling',
>                 '--user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.3'
>             ],
>             executablePath: "/usr/bin/chromium-browser",
>         });
>         this.browser = browser;
> ```

I get this error

Unhandled promise rejection: Error: Failed to launch the browser process! spawn /usr/bin/chromium-browser ENOENT

**Comment by zyx-24** [comment]
> Just go to `~/node_modules/node_characterai/requester.js` and on line 39, you'll see this:
> 
> ```js
>         const browser = await puppeteer.launch({
>             headless: this.#headless,
>             args: [
>                 '--fast-start',
>                 '--disable-extensions',
>                 '--no-sandbox',
>                 '--disable-setuid-sandbox',
>                 '--no-gpu',
>                 '--disable-background-timer-throttling',
>                 '--disable-renderer-backgrounding',
>                 '--override-plugin-power-saver-for-testing=never',
>                 '--disable-extensions-http-throttling',
>                 '--user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.3'
>             ]
>         });
>         this.browser = browser;
> ```
> 
> Add this to line 39:
> 
> ```js
> executablePath: "/usr/bin/chromium-browser"
> ```
> 
> And now it should look like this:
> 
> ```js
>         const browser = await puppeteer.launch({
>             headless: this.#headless,
>             args: [
>                 '--fast-start',
>                 '--disable-extensions',
>                 '--no-sandbox',
>                 '--disable-setuid-sandbox',
>                 '--no-gpu',
>                 '--disable-background-timer-throttling',
>                 '--disable-renderer-backgrounding',
>                 '--override-plugin-power-saver-for-testing=never',
>                 '--disable-extensions-http-throttling',
>                 '--user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.3'
>             ],
>             executablePath: "/usr/bin/chromium-browser",
>         });
>         this.browser = browser;
> ```

I get this error

Unhandled promise rejection: Error: Failed to launch the browser process! spawn /usr/bin/chromium-browser ENOENT

**Comment by realcoloride** [comment]
ENOENT means no such file or directory so that is an error on your end

**Comment by Parking-Master** [comment]
@zyx-24 that path was written for Raspberry Pi. If your OS is different, you need to look for another path that chromium is in. Try `find / -iname "chromium-browser"` and make sure chromium is actually installed.

**Comment by realcoloride** [comment]
See here:
https://github.com/realcoloride/node_characterai/commit/06aca019527ee81492fe746f70120133a3f51424

Sorry if I cant fix all the issues you have on Linux as I don't have linux and puppeteer also annoys me to use.

**Comment by Parking-Master** [comment]
That’s ok if you can’t do it. If you want linux for free in the future, you can try using VirtualBox (I heard you are on windows, it should work on there) and just download a basic version of Raspbian on the Virtual machine from their official website. I’ve done it before and it’s fairly easy, just use some online tutorial. Anyways, thanks for fixing the problems!

**Comment by realcoloride** [comment]
Hello,
To OP or members of the thread, please re-open this or a new an issue if issues persist.
