### ISSUE TITLE
.getMessageById always returns null

### ISSUE THREAD

**Issue by Xtr4F** [realcoloride/node_characterai#54]
I have a code that gets a message by its id

![image](https://github.com/realcoloride/node_characterai/assets/105001002/6f2dbf8f-511b-4e93-bba4-09fd746934aa)
But it always returns null, no matter which id I try.

If anything, there is no error in the id. Character ai gives me the same id:

![image_2023-06-06_21-28-23](https://github.com/realcoloride/node_characterai/assets/105001002/0f496689-8015-45b7-9316-ec8a184f3524)

I tried to print out the ids it receives:

![image](https://github.com/realcoloride/node_characterai/assets/105001002/e50e00ae-2888-437c-8c09-8f95a05ecc5e)

I'm new to node, but I think the whole reason is BigNumber. Or maybe I don't understand something.

**Comment by realcoloride** [comment]
Hello, this seems weird, I will try to look and investigate into the issue.
