### ISSUE TITLE
¿error 1.1.4?

### ISSUE THREAD

**Issue by LucasAlgerDay** [realcoloride/node_characterai#57]
I create an api with the code, that problem give me with login (token)
![image](https://github.com/realcoloride/node_characterai/assets/88118098/3a7045a0-5458-4546-8bfb-11ec5cc170e9)

I tried with login as guest and it works fine
![image](https://github.com/realcoloride/node_characterai/assets/88118098/0d7c6eb6-4c46-45bd-834b-5bdbe00979e6)

**Comment by LucasAlgerDay** [comment]
I tried with the full token but its the same
![image](https://github.com/realcoloride/node_characterai/assets/88118098/09cd590f-6de0-41b5-8e29-4905dfd9e0ce)

**Comment by realcoloride** [comment]
Hello this is weird, I will investigte on this issue.

**Comment by kennex666** [comment]
I have the same issue.

**Comment by Fubuki-World0510** [comment]
try version 1.1.3

**Comment by realcoloride** [comment]
Hello, could you try switching to the old `headless = true` in requester.js and tell me the result?

**Comment by realcoloride** [comment]
![Code_vEUIOyPMGb](https://github.com/realcoloride/node_characterai/assets/108619637/94738a7a-e1aa-4ff2-8a5a-c6d844991b89)
Upon investigation, it seems like its an issue with the waiting room. I will make a workaround for that.

**Comment by realcoloride** [comment]
Hello, I've pushed a temporary update `1.1.5` that should fix some of the problems. Could you try this update and tell me how it goes?

**Comment by LucasAlgerDay** [comment]
![image](https://github.com/realcoloride/node_characterai/assets/88118098/ea6b83ec-6d07-450a-9c12-7443ad6e8420)
its the 1.1.5
![image](https://github.com/realcoloride/node_characterai/assets/88118098/82db2e1d-27fe-4f4e-8696-2e02bfef28e9)

**Comment by LucasAlgerDay** [comment]
![image](https://github.com/realcoloride/node_characterai/assets/88118098/8f379796-2ab8-4817-b294-36041cd520d5)
and it

**Comment by realcoloride** [comment]
Are you sure this is the latest 1.1.5 build?
