### ISSUE TITLE
Include message deletion

### ISSUE THREAD

**Issue by eliangerard** [realcoloride/node_characterai#6]
There is a problem with the Character AI website and its bots because after chatting for a while, they start responding with the same messages over and over again. According to users, a solution is to delete the messages in the conversation from where it started repeating. Would it be possible to add this function to the package? Maybe delete the history or something

![image](https://user-images.githubusercontent.com/72888646/221103733-df73f121-d365-4fa5-8dc9-77504cd3f31d.png)

Thank you for reading!

**Comment by realcoloride** [comment]
I do agree it would be great but I have no idea on how to implement that
yet, I'll think about it and see. If you know to implement it let me know.

Le ven. 24 févr. 2023 à 07:02, Elian Gerard ***@***.***> a
écrit :

**Comment by realcoloride** [comment]
Issue revoled in #10
