### ISSUE TITLE
It stops after one run like it runs once but i need to re run every time 

### ISSUE THREAD

**Issue by furkanshaikh313** [realcoloride/node_characterai#65]
C:\Users\HP>node "c:\Users\HP\Desktop\node_characterai-main\const CharacterAI = require('node_charac.js"
[node_characterai] Puppeteer - This is an experimental feature. Please report any issues on github.
[node_characterai] Puppeteer - Done with setup
[node_characterai] Puppeteer - Eval-fetching is an experimental feature and may be slower. Please report any issues on github
No! Not my soul!

**Comment by realcoloride** [comment]
Could you specify more details?

**Comment by furkanshaikh313** [comment]
Dont worry i fixed it

**Comment by Parking-Master** [comment]
You can close this issue now since it has been resolved.
