### ISSUE TITLE
Support for typescript?

### ISSUE THREAD

**Issue by ArkanDash** [realcoloride/node_characterai#69]
Is there will be support for the typescript?
Currently cannot do `npm i --save-dev @types/node_characterai` because it does not exist.
It would be better to support typescript as well.

**Comment by ArkanDash** [comment]
What I mean is support for typescript types.

**Comment by Kaidesa** [comment]
> Is there will be support for the typescript?

You can easily just manually download the package and add this into tsconfig.json

```json
{
  "compilerOptions": {
    ...
    "allowJs": true,
    "checkJs": false,
    ...
  }
}
```

Then use

```ts
import * as node_characterai from './../includes/node_characterai';
```

Or wherever you saved it to.  It's kind of hacky, but it should work just fine.

**Comment by Parking-Master** [comment]
If this issue was resolved, it's safe to close it now
