### ISSUE TITLE
I cant see any token

### ISSUE THREAD

**Issue by furkanshaikh313** [realcoloride/node_characterai#71]
Is Charecter AI updated i cant find any token key

**Comment by rama4zis** [comment]
Are you already log in? Just make sure to follow the step correctly

**Comment by furkanshaikh313** [comment]
ok

**Comment by Parking-Master** [comment]
Follow the instructions in this repo's docs. In chrome/firefox, go to https://beta.character.ai/ (and make sure to log in on the site). Then open the developer console (search it up if you don't know how) and go to Application > Storage > Local Storage. Then find `https://beta.character.ai` and expand the tab. You will see "body" on the right. Expand that with the arrow and copy the access token nested inside it. Now you have your access token, so authenticate node_characterai with it.
