### ISSUE TITLE
Authentication hanging bug

### ISSUE THREAD

**Issue by Parking-Master** [realcoloride/node_characterai#73]
Greetings again!

I am here suggesting another fix in case this is happening for anyone else.

It seems that when authenticating Character.AI, the site (in puppeteer) already has the token stored in localStorage (don't ask me why, but it's super insecure).

If your script says "[node_characterai] Puppeteer - Done with setup" and never sends any messages to the AI, it's for the reason that you are already authenticated and the script hangs because it waits for the site to authenticate you.

I just found a workaround where all you have to do is clear the site's `localStorage` for it to work every time you run the script.

This ensures EVERYTHING is cleared on beta.character.ai, not just cookies/cache.

Feel free to make a commit with the following code :)

###### node_modules/node_characterai/requester.js:46
```javascript
await page.evaluate(() => localStorage.clear());
```

Right after this line:
```javascript
await page.goto("https://beta.character.ai");
```

(Line 46 of requester.js)

**Comment by realcoloride** [comment]
Hello, I will investigate and consider this issue.

**Comment by Parking-Master** [comment]
@realcoloride Thanks, if you test it let me know how it goes

**Comment by Parking-Master** [comment]
@realcoloride seems another user had this problem (#75) and my solution worked

**Comment by ohsyme** [comment]
> 

ERROR: The process with PID 15164 (child process of PID 4688) could not be terminated.
Reason: The operation attempted is not supported.
ERROR: The process with PID 14576 (child process of PID 4688) could not be terminated.
Reason: The operation attempted is not supported.
ERROR: The process with PID 7856 (child process of PID 4688) could not be terminated.
Reason: The operation attempted is not supported.
ERROR: The process with PID 10260 (child process of PID 4688) could not be terminated.
Reason: The operation attempted is not supported.
ERROR: The process with PID 2136 (child process of PID 4688) could not be terminated.
Reason: The operation attempted is not supported.
ERROR: The process with PID 6656 (child process of PID 4688) could not be terminated.
Reason: The operation attempted is not supported.
ERROR: The process with PID 4688 (child process of PID 2040) could not be terminated.
Reason: There is no running instance of the task.


after i put that inside requester i always get this errors

**Comment by Parking-Master** [comment]
@ohsyme it's already been added to the package, just reinstall it and use it

**Comment by Parking-Master** [comment]
@ohsyme see #78

**Comment by ohsyme** [comment]
> @ohsyme see #78

thank you its working after i change the version to 1.1.3

**Comment by Parking-Master** [comment]
@ohsyme great to hear! We're still working on a fix for the latest version. For now just use 1.1.3 though :)

**Comment by realcoloride** [comment]
@Parking-Master i think there might need to rework and inherit from 1.1.3 because of the current issues

**Comment by Parking-Master** [comment]
@realcoloride first I would like to test if we just need to change one file instead of rolling back all of them to an older version

**Comment by Parking-Master** [comment]
If you roll back the version completely, you will need to re-add all of the newer functions (like waitInWaitingRoom, etc.) so I don't think it's a good idea to do that.

This is just a recommendation though, you can do what you want, but just a warning some things won't work on there.

**Comment by realcoloride** [comment]
If possible I need to review the changes made through out the versions and then make a stable version from 1.1.3
I am really sorry that the newer versions have became unstable and I will try my best to fix it.

**Comment by Parking-Master** [comment]
@realcoloride don't worry about it! If it works I will happily wait for you to take all the time you need to fix it. Let me know if I can help you too, that would be great :)

**Comment by realcoloride** [comment]
hey @Parking-Master could i contact you somewhere?

**Comment by Parking-Master** [comment]
@realcoloride yep, use my email parkingmaster@email.com

**Comment by realcoloride** [comment]
do you have discord by any chance?

**Comment by Parking-Master** [comment]
No, why?

**Comment by realcoloride** [comment]
Because that would be better for communication (atleast to me)

**Comment by Parking-Master** [comment]
Yeah I don't think I have discord, I remember using it years ago but not now lol. You can contact me using my email I posted, I'll respond

**Comment by feelinSleepy** [comment]
Been running into this issue as of late. I got a Discord chatbot that I'm running off with this API, flawless for the most part, till one day it stopped working.  Finally got around to debugging, this seems to be the issue. Gets hung up on the authentication and never moves forward.

Not sure that it's important, but just to note I'm running this headlessly on a Raspberry Pi 3B+

I've tried some steps are remediation but not to any major success.

Originally I was on 1.1.9, tried the above fix, with no success. 
I tried downgrading to 1.1.3, but it turns out a variable I need to get this configured properly to run on Linux isn't there. 
So, I went up to 1.1.4, the first version where I got everything working great.
From there, still no luck. Combined 1.1.4 setup + the above fix, and it worked! Once. Hasn't worked after that.

I decided to let it run for a bit to see if maybe it was going to work eventually and was just a bit slow, but only ended up with a timeout error. I'll attach it below, just incase you guys wanna see.

<img width="670" alt="image" src="https://github.com/realcoloride/node_characterai/assets/42017647/64e9e8e7-b44c-4167-9e05-87d536110a6f">

Not sure what other measures to take, I'm sorry if I missed something that makes this an easy fix. It's 1AM and I'm just trying to get this fixed haha. Have a great night you guys, love this project.

**Comment by Parking-Master** [comment]
@feelinSleepy I guess the username goes then lol.

The error in the picture means the page timed out. If you open https://beta.character.ai for some reason in puppeteer, it never loads. I found out the problem about last week (#74).

It has to do with cloudflare detecting bots. I don't know how but they've got this magic software that can easily detect puppeteer like it's nothing. Once @realcoloride gets the version rolled back to 1.1.3 and fixes the newer issues, we'll investigate this issue.

Thanks for your response.

**Comment by realcoloride** [comment]
Hey there!

Could you try adding the page.evaluate() fix from @parking-master and see if it works? thank you.
I'll keep you updated.

**Comment by Parking-Master** [comment]
@realcoloride

> From there, still no luck. Combined 1.1.4 setup + the above fix, and it worked! Once. Hasn't worked after that.

**Comment by realcoloride** [comment]
> @realcoloride
> 
> > From there, still no luck. Combined 1.1.4 setup + the above fix, and it worked! Once. Hasn't worked after that.

Yes I know, but does the 1.1.4 contain the page evaluate fix?

**Comment by Parking-Master** [comment]
Yep, the OP said they tried the above fix, and it worked _once_, so it did work but stopped after that

**Comment by feelinSleepy** [comment]
> Hey there!
> 
> Could you try adding the page.evaluate() fix from @Parking-Master and see if it works? thank you. I'll keep you updated.
> 
> Oh and by the way there is a typo that was corrected in newer versions there: ![chrome_Gpz4tumafO](https://user-images.githubusercontent.com/108619637/262726065-c0c596b3-677e-4b4d-8327-b5e5f46a52b6.png)
> 
> status => status()
> 
> It was corrected in newer versions.

Yeah, I've already added that in last night, sadly no luck.
Also I know overwriting the whole package is dumb, but I'm just a dumb person haha. I usually bang things together until they work.
I'll try to go in and fix that typo when I can!

**Comment by feelinSleepy** [comment]
> @feelinSleepy I guess the username goes then lol.
> 
> The error in the picture means the page timed out. If you open https://beta.character.ai for some reason in puppeteer, it never loads. I found out the problem about last week (#74).
> 
> It has to do with cloudflare detecting bots. I don't know how but they've got this magic software that can easily detect puppeteer like it's nothing. Once @realcoloride gets the version rolled back to 1.1.3 and fixes the newer issues, we'll investigate this issue.
> 
> > I tried downgrading to 1.1.3, but it turns out a variable I need to get this configured properly to run on Linux isn't there.
> 
> Also if you don't mind, what variable did you mean, is it in puppeteer/node_characterai?
> 
> Also, if this helps, I couldn't get node_characterai working on a Raspberry Pi 4B but I just needed to add the path to chromium:
> 
> [#53 (comment)](https://github.com/realcoloride/node_characterai/issues/53#issuecomment-1580871902)
> 
> Thanks for your response.

The variable is the called puppeteerPath or something along those lines, not present in 1.1.3 requester.js but is in 1.1.4 requester.js

Generally to get this working on Debian(or any Linux flavor usually), you just have to add the correct path for Puppeteer to launch Chromium from. I'm not technologically inclined enough to mess with Puppeteer itself and change that, but I figured out that variable in requester.js easy enough. I can try digging through Puppeteer and seeing if I can find it there.

**Comment by Parking-Master** [comment]
@feelinSleepy did you see the comment I linked? The path is "/usr/bin/chromium-browser". It works great after adding that

**Comment by Parking-Master** [comment]
So then it works?

**Comment by feelinSleepy** [comment]
> > Yeah, that's what I did on 1.1.4 and above to get it working. There's a place to put it in requester.js. Just not sure that 1.1.3 has the option for it without going through Puppeteer directly, it may have one, I just might've overlooked it
> 
> So then it works now?

No, it doesn't. The issue I'm having is related to it getting hung up on the authentication, and I can't exactly downgrade all the way to 1.1.3 and try to remedy that way. Just thought I'd update the closest issue with my info.

**Comment by Parking-Master** [comment]
@feelinSleepy ok, thank you so much for this information!

I will try to create a pull request by next week that fixes all of everyone's problems and I will base it on v1.1.3 for speed and reliability.

Thanks for your patience :)

**Comment by feelinSleepy** [comment]
> @feelinSleepy ok, thank you so much for this information!
> 
> I will try to create a pull request by next week that fixes all of everyone's problems and I will base it on v1.1.3 for speed and reliability.
> 
> Thanks for your patience :)

Not a problem at all! Thanks for all your work, my friends love what I've been able to cook up with this haha, but it wouldnt be possible without you guys

**Comment by realcoloride** [comment]
> @realcoloride if you don't mind, if you didn't already start trying to fix the newer versions, could you wait until next week and I'll send a pull request with a fixed/faster version (based on 1.1.3)?

That would help a lot, if you could cite changes exactly, I am investigating and doing a bunch of tests with cloudflare and puppeteer to see whats best at the moment

**Comment by Parking-Master** [comment]
@realcoloride thanks. I'll give you an update next Saturday, along with a pull request

**Comment by Parking-Master** [comment]
Update: See #80

**Comment by Parking-Master** [comment]
@feelinSleepy thanks for your patience! The official update with fixes was pushed. Please try it now!

**Comment by feelinSleepy** [comment]
> @feelinSleepy thanks for your patience! The official update with fixes was pushed. Please try it now!

Hey! Just updated your package and tried it, no luck sadly :,)

It seems to complete the setup, it just never actually authenticates for some reason. I've tried it with the above fix as well, with no real changes.

I've also tried using the fork from @Parking-Master, same issue there too.

Thanks for all your hard work guys, I really appreciate it.

**Comment by Parking-Master** [comment]
Oh... sorry about that. Why does cloudflare have to make things so complicated? If CAI doesn't want an unofficial API, they should clarify that in their ToS. Instead of sliently blocking the API.

I'll see what's wrong and get back to you soon!
