### ISSUE TITLE
stuck?

### ISSUE THREAD

**Issue by ohsyme** [realcoloride/node_characterai#77]
![image](https://github.com/realcoloride/node_characterai/assets/49177554/94d9e22c-8560-4fdf-a94a-4f7f975c3bfd)
after i put my token inside characterAI.authenticateWithToken its stuck smh but when i turn to guess mode its normal xd

**Comment by Parking-Master** [comment]
Try installing 1.1.3 instead, for some reason it's working much better than the latest version
```bash
npm install node_characterai@1.1.3
```
