### ISSUE TITLE
Messing around with that waifu thing, ERROR: The process "27224" not found. Cannot read properties of undefined (reading 'find') node

### ISSUE THREAD

**Issue by goodiesohhi** [realcoloride/node_characterai#78]
node js: Unable to send message.
node js: CharacterAI is still fetching character data!
node js: If it's taking far too long please submit an issue.
node js: [node_characterai] Puppeteer - Currently in cloudflare's waiting room. Time left: 3
node js: [node_characterai] Puppeteer - Currently in cloudflare's waiting room. Time left: 2
node js: [node_characterai] Puppeteer - Done with setup
node js: Authenticated, fetching character AI info....
node js: ERROR: The process "27224" not found.
node js: D:\waifu\character_ai\chat.js:12
node js:         const ai = continueBody.participants.find(
node js:                                              ^
node js:
node js: TypeError: Cannot read properties of undefined (reading 'find')
node js:     at new Chat (D:\waifu\character_ai\chat.js:12:46)
node js:     at Client.createOrContinueChat (D:\waifu\character_ai\client.js:164:20)
node js:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
node js:     at async main (D:\waifu\character_ai\runner.js:57:26)

I spent some time poking around but I can't seem to figure it out.

**Comment by ByteLabDev** [comment]
Same issue, their website says they're experiencing high traffic. Maybe it's that?
![image](https://github.com/realcoloride/node_characterai/assets/67926878/4f57548b-c852-44fe-93d3-4d132d98547c)

**Comment by Parking-Master** [comment]
It's because you're using waifu. They are using a really old version of characterai and the API is completely different.

Also see #68

You need to delete node_characterai wherever it's located in the desktop-waifu package, then re-install it manually like this:

```bash
cd node_modules/desktop-waifu/tree/master/
rm -rf character_ai
git clone https://github.com/realcoloride/node_characterai.git
mv node_characterai character_ai
```

These commands go into the folder containing the old `character_ai` code, removes the old folder, clones the new repo in, then renames it (because waifu uses a different name for the folder).

Please try this code (make sure you do it in the directory containing the `node_modules` folder) and let me know how it goes :)

**Comment by goodiesohhi** [comment]
node js: node:internal/modules/cjs/loader:959
node js:   throw err;
node js:   ^
node js:
node js: Error: Cannot find module 'D:\gwenniebot\gwenniebot\character_ai\runner.js'
node js:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
node js:     at Function.Module._load (node:internal/modules/cjs/loader:804:27)
node js:     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
node js:     at node:internal/main/run_main_module:17:47 {
node js:   code: 'MODULE_NOT_FOUND',
node js:   requireStack: []
node js: }

**Comment by goodiesohhi** [comment]
Also noticed that when waifu is installing dependencies.
This happens:
Building cache. Hang on . . .
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\waifu\waifu\Lib\site-packages\pipwin\__main__.py", line 4, in <module>
    main()
  File "D:\waifu\waifu\Lib\site-packages\pipwin\command.py", line 84, in main
    cache = pipwin.PipwinCache()
            ^^^^^^^^^^^^^^^^^^^^
  File "D:\waifu\waifu\Lib\site-packages\pipwin\pipwin.py", line 210, in __init__
    self.data = build_cache()
                ^^^^^^^^^^^^^
  File "D:\waifu\waifu\Lib\site-packages\pipwin\pipwin.py", line 103, in build_cache
    dl_function = re.search(r"function dl.*\}", soup.find("script").string).group(0)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'

pipwin is like discontinued right. Could this be an issue as well?

**Comment by Parking-Master** [comment]
@goodiesohhi  try creating the old runner.js file and copying the file contents from the repository, then do the same for any other files that are required.

here's the files that aren't already included in node_characterai:

https://github.com/AlizerUncaged/desktop-waifu/blob/master/character_ai/yarn.lock

https://github.com/AlizerUncaged/desktop-waifu/blob/master/character_ai/.gitignore

https://github.com/AlizerUncaged/desktop-waifu/blob/master/character_ai/runner.js

**Comment by Parking-Master** [comment]
PS: the latest version `node_characterai` lacks performance and doesn't work some of the time, so I recommend cloning characterai version 1.1.3 instead.

```bash
cd node_modules/desktop-waifu/
rm -rf character_ai
git clone https://github.com/realcoloride/node_characterai.git
cd node_characterai
git checkout 152ac69
cd -
mv node_characterai character_ai
```

All of this code will do the same thing as last time, except with the `git checkout` so it goes back to the latest commit of v1.1.3.

**Comment by goodiesohhi** [comment]
> PS: the latest version `node_characterai` lacks performance and doesn't work some of the time, so I recommend cloning characterai version 1.1.3 instead.
> 
> ```shell
> cd node_modules/desktop-waifu/
> rm -rf character_ai
> git clone https://github.com/realcoloride/node_characterai.git
> cd node_characterai
> git checkout 152ac69
> cd -
> mv node_characterai character_ai
> ```
> 
> All of these commands will do the same thing as last time, except with the `git checkout` so it goes back to the latest commit of v1.1.3.
> 
> After you do this, try adding in the files a linked and see if it works. Thanks for responding by the way

Authentication request sent to VTube Studio, please click allow.
node js: D:\waifu\character_ai\chat.js:11
node js:         const ai = continueBody.participants.find(
node js:                                              ^
node js:
node js: TypeError: Cannot read properties of undefined (reading 'find')
node js:     at new Chat (D:\waifu\character_ai\chat.js:11:46)
node js:     at Client.createOrContinueChat (D:\waifu\character_ai\client.js:164:20)
node js:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
node js:     at async main (D:\waifu\character_ai\runner.js:57:26)
VTube Studio connected! at port 8001
You (mic) > you
Traceback (most recent call last):
  File "D:\waifu\waifu\Src\runner.py", line 147, in <module>
    utils.characterAi.send_message_to_process_via_websocket(transcript)
  File "D:\waifu\waifu\Src\utils\characterAi.py", line 31, in send_message_to_process_via_websocket
    ws.send(message)
  File "D:\waifu\waifu\Lib\site-packages\websocket\_app.py", line 240, in send
    raise WebSocketConnectionClosedException(
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.
node js
Press any key to continue . . .

**Comment by Parking-Master** [comment]
This is getting annoying... I'll look into soon

**Comment by Parking-Master** [comment]
@goodiesohhi I noticed it gets stuck on an error right after it's "authenticating"... have you checked that you have the right auth token and character id?

**Comment by goodiesohhi** [comment]
I checked the initializer where it uses the response from the api for continuebody to create a new ai and I found that instead of character information the body of the response is no character found for <character id>.
Otherwise it seems to be authing properly and the character id is the correct one found in the parameter of the url so what could be wrong?

**Comment by Parking-Master** [comment]
https://beta.character.ai/chat?char=_pWH5J4crWL3NaxPWIO2szDQedihAquHbDrkXH90rw

It says not found

**Comment by Parking-Master** [comment]
> I checked the initializer where it uses the response from the api for continuebody to create a new ai and I found that instead of character information the body of the response is "no character found for character id here".

try with a popular character like "Character.AI Assistant" (YntB_ZeqRq2l_aVf2gWDCZl4oBttQzDvhj9cXafWcF8)

**Comment by goodiesohhi** [comment]
> > I checked the initializer where it uses the response from the api for continuebody to create a new ai and I found that instead of character information the body of the response is "no character found for character id here".
> 
> try with a popular character like "Character.AI Assistant" (YntB_ZeqRq2l_aVf2gWDCZl4oBttQzDvhj9cXafWcF8)
OH. I figured it out.. You typing the link to me made me realize the id is actually
-_pWH5J4crWL3NaxPWIO2szDQedihAquHbDrkXH90rw
dowieieieieiei.
Anyways one last bug to iron out which is that the spoken text is only interpreted as "you" lol

**Comment by goodiesohhi** [comment]
And there we go it is completely working. The pyaudio library just was using my default microphone which wasn't my microphone I was using, just needed to mess around with my settings instead of actually selecting the right device in python but it works. 
Basically, download the waifu library, download the files parking master suggested and replaces waifu's copies. If you get the npm-cli library is missing error like I did and a lot of other people did, u can simply copy and paste that from ur npm install to the modules in waifu. Then there are just a whole bunch of lines where waifu is using the older api or is otherwise broken, fix them one by one and you're done :>

**Comment by Parking-Master** [comment]
@goodiesohhi good to hear!

**Comment by goodiesohhi** [comment]
> @goodiesohhi good to hear!

Yeah thanks for all the help, you were very wonderful, definitely couldn't have figured it out without you :>

**Comment by Parking-Master** [comment]
@goodiesohhi thank you so much!
