### ISSUE TITLE
Using the module in Next js

### ISSUE THREAD

**Issue by monmon0** [realcoloride/node_characterai#79]
Hello! First of all, thank you for building the project.

I'm currently trying to integrate the api in a Next js project. However, im encoutering this error:
Cannot statically analyse 'require(…, …)'

Any help would be appreciated, tysm!

**Comment by Parking-Master** [comment]
@monmon0 why does it show two arguments in `require()`L

**Comment by realcoloride** [comment]
Hello, is your problem solved?

**Comment by realcoloride** [comment]
Hello, since this has not been updated in quite some time, please re open an issue if you are having problems again
