### ISSUE TITLE
[Feature suggestion] Memory wipe

### ISSUE THREAD

**Issue by ClownOfMadness** [realcoloride/node_characterai#8]
just a suggestion that can be very helpful. If the user uses non guest authorization
Have a function that wipes all the conversation and creates a new conversation with no memory of the previous one

There is such option in character AI website "Save and Start New Chat"
![image](https://user-images.githubusercontent.com/52707645/221189734-6f4eeadd-afd2-4dbe-938d-8a25ab87d1ec.png)

**Comment by realcoloride** [comment]
sounds good! I will try to see how it works and try to implement it.

**Comment by realcoloride** [comment]
Hello! 

I implemented what you asked and also did add a couple of other features:
* `chat.saveAndStartNewChat()` - Creates and saves the current chat
* `chat.getSavedConversations(amount = 50)` - Get all past saved conversations and their information (amount in parameters)
* `chat.changeToConversationId(conversationExternalId, force = false)` - Change to a specific conversation id, force means that it doesn't check if the conversation existed before (this may lead to errors)

In correlation to issue #6, this may help in the following of your request and their request.
I am finishing testing and publishing the update soon.

**Comment by realcoloride** [comment]
Also changed `createOrContinueChat()`:
The arguments now include `(characterId, externalId)`

Now, instead of always creating a new chat, you can specify to continue the chat via a specific conversation externalId.

**Comment by realcoloride** [comment]
![image](https://user-images.githubusercontent.com/108619637/221248130-221b51ca-d004-445d-94b8-1ecc45a1b321.png)
![image](https://user-images.githubusercontent.com/108619637/221248149-aae490d5-9e8a-4778-843b-66898ee76d1a.png)

![image](https://user-images.githubusercontent.com/108619637/221248171-1b66cee3-6211-4999-bf88-37815896ff76.png)

The update `1.0.22` was published after some testing.
If you find any bugs or problems please let me know.

Next update may be focused on message deleting/bulk message deletion.

**Comment by ClownOfMadness** [comment]
wow this is great! thank you!

I tried using it now, not sure if I used it correctly but i get this error:
![image](https://user-images.githubusercontent.com/52707645/221282479-53c0703f-6b76-41ef-a1a5-07747f743f41.png)
And yes, I did update it

**Comment by realcoloride** [comment]
hmm thats weird, could you give the code and recheck the package version?

**Comment by ClownOfMadness** [comment]
here is the snippet of the code where i use it
![image](https://user-images.githubusercontent.com/52707645/221291600-50b5bac4-d47f-4d83-80fd-51ba9fdcbd36.png)

and here is the version i use:
![image](https://user-images.githubusercontent.com/52707645/221291807-429e9fb4-17e6-43e8-8939-f1d25a662f9f.png)

**Comment by realcoloride** [comment]
I think that whats happening may be that something wrong happened in your create or continue chat. could you give the character id you use?

**Comment by ClownOfMadness** [comment]
um sure, it is 2B
`csTC3hw0Fnj1Whnl0uV1Nb3_oYIillMQtdBH5NEl0Gs`

**Comment by realcoloride** [comment]
![image](https://user-images.githubusercontent.com/108619637/221318971-30d5c0e7-6362-4c52-926d-500fa868c8d6.png)
it worke perfectly fine for me.
![image](https://user-images.githubusercontent.com/108619637/221318993-ffd5036c-82ba-4c69-9015-75535164feb7.png)

I don't know why this doesn't work for you. Are you using a guest account?

**Comment by ClownOfMadness** [comment]
oh i see now, it would not work unless i send a message to the ai.
once i added the `sendAndAwaitResponse` it works!

Thank you!
