### ISSUE TITLE
Current implemented fixes

### ISSUE THREAD

**Issue by Parking-Master** [realcoloride/node_characterai#80]
By 9/2/23, this list will be complete.

I've been working on this package, and building a newer version of `node_characterai` that is based on 1.1.3.

Sometimes you just need a fresh start, lol.

- [x] Fix performance issues
- [x] Make some features easier for plus users
- [x] Implemented newer features and functions
- [x] Fixed all bugs from recent issues (from temporary fixes)
- [x] Cleaned/formatted code

And just a minor thing too - I need feedback @realcoloride whether I should remove this message:
> [node_characterai] Puppeteer - Eval-fetching is an experimental feature and may be slower. Please report any issues on github

I've experimented with axios, http, https, and fetch, but none of them are better or they don't work at all.

Should I remove that message?

**Comment by Parking-Master** [comment]
Update: It seems that when adding `waitForWaitingRoom` in 1.1.3, it prevents characterai from authenticating. Still investigating.

**Comment by realcoloride** [comment]
Hello, keep the printing statement. Keep up with the good work!

**Comment by Parking-Master** [comment]
Update: With my working version so far, it takes __12.9 seconds__ to complete setup.

With the current/latest version, it takes __22.6 seconds__ to complete setup (I know, annoyingly long)

It's about a 10-second difference in total.

**Comment by Parking-Master** [comment]
Also, the current fixed version is at https://github.com/Parking-Master/node_characterai

You can install it using:
```
npm install git+https://github.com/Parking-Master/node_characterai.git -g --prefix ./node_modules
```

And find the folder where `node_characterai` is.

**Comment by realcoloride** [comment]
Hey parking master, could you check if the README matches? with the newest? and could you perhaps make the commits here so they can directly be pushed?

**Comment by Parking-Master** [comment]
> Hey parking master, could you check if the README matches? with the newest? and could you perhaps make the commits here so they can directly be pushed?
Thanks again for the crazy work!

No problem! I'll check what I need to change on the README tomorrow.

Also, I'll make the forked repo into a pull request with all the commits once I'm done.

**Comment by Parking-Master** [comment]
Update: See https://github.com/Parking-Master/node_characterai/blob/main/README.md (https://github.com/Parking-Master/node_characterai/commit/ef76f0e54dfa8e6133e0b453f2173e9a7ee6f42f), and #81

**Comment by Parking-Master** [comment]
Feel free to edit the docs and code to your liking.

**Comment by Parking-Master** [comment]
List done! I will let you and some other users test it before pushing it on Saturday.
