### ISSUE TITLE
stuck at "Puppeteer - Done with setup". already tried some workarounds, still doesnt work

### ISSUE THREAD

**Issue by Yuan-San** [realcoloride/node_characterai#82]
Hello, I am currently making a discord bot hosted locally using this API. I tried to follow the README.md, but it doesn't work and discord.js keeps throwing "cannot send an empty message" then I tried to authenticate as a user. I think I got my token right, but it somehow hangs in "Puppeteer - Done with setup". I tried searching for similar issues here and followed #62, #68, and #73. but now after more tries the issue varies between `Cannot read properties of undefined (reading 'status')`, hangs at authentication, and sometimes back to `DiscordAPIError[50006]: Cannot send an empty message

![image](https://github.com/realcoloride/node_characterai/assets/67492199/ce313cbc-df97-476d-958c-ecde9f530465)
![image](https://github.com/realcoloride/node_characterai/assets/67492199/efb0e7bf-241f-4bda-97e8-03cbf152b095)
![image](https://github.com/realcoloride/node_characterai/assets/67492199/31a3136f-ada5-49ab-83dd-c95a855ccb47)

note: These errors happen over the span of 5 minutes

**Comment by EmmaScripted** [comment]
same thing happening to me. it seems to happen if you use a token to log in for some reason? maybe character.ai is doing some sort of scrapping detection and preventing it idk
![image](https://github.com/realcoloride/node_characterai/assets/61598574/305b66e1-8a0f-4a72-a2ce-566229ca6108)

**Comment by Parking-Master** [comment]
Hello, and thanks for opening this issue. See #80. Me and @realcoloride are working on a fix and will be pushed this upcoming Saturday (the 2nd).

Could you run this:
```bash
git clone https://github.com/Parking-Master/node_characterai
```

And import it like this:
```javascript
const CharacterAI = require("./node_characterai/index.js");
```

This will use my current forked version with bug fixes and newer functions.

Please let me know how it goes!

**Comment by EmmaScripted** [comment]
i had the same issue and the updated github had issues and it still didnt work, but for some reason when i changed this line to code to this, it started working???? what
![image](https://github.com/realcoloride/node_characterai/assets/61598574/db7cd152-842f-454d-874f-353d96e9f5a9)
![image](https://github.com/realcoloride/node_characterai/assets/61598574/29b7bb12-6b77-4b93-ba17-fdb8114858e9)

**Comment by Yuan-San** [comment]
Thanks, @Parking-Master ! It works miraculously better now, and I have not received any issues since. Thank you again!

**Comment by ant0n-0x0000** [comment]
> Thanks, @Parking-Master ! It works miraculously better now, and I have not received any issues since. Thank you again!

I had the same issue as you but after this fix, I'm still getting the TypeError. Would you be able to share your repo with me so I can see where I'm going wrong?

**Comment by Parking-Master** [comment]
@ant0n-0x0000 I'd like to help you with this problem, so I can implement any fixes in my current working version. If you can, could you paste the exact error and the code you're receiving it from? Thanks!

**Comment by ant0n-0x0000** [comment]
@Parking-Master
An error occurred during chat response: `TypeError: Cannot read properties of undefined (reading 'status')`
    at Chat.sendAndAwaitResponse (C:\Users\ant0n\WebstormProjects\discord-ai\node_characterai\chat.js:65:21)
    at async Client.<anonymous> (C:\Users\ant0n\WebstormProjects\discord-ai\main.js:28:38)

**Comment by Parking-Master** [comment]
@ant0n-0x0000 nope, this is a common error in this package, lol. I'll try to get back with a fix in about an hour.

**Comment by ant0n-0x0000** [comment]
@Parking-Master If you'd like to see my code, you can add me on discord @ant0n and we can discuss it there, then we can update this if we find something?

**Comment by Parking-Master** [comment]
@ant0n-0x0000 sorry but I don't have discord. Also this isn't your fault, this error has been happening for a very long time (check older closed issues if you don't believe me 😂).

I'll fix it ASAP and keep you up to date.

**Comment by Parking-Master** [comment]
Update: I found a similar issue to yours. I tried the solution in it and it seems to have worked faster and doesn't time out anymore. Could you re-clone the repo and try it again? Thanks.

**Comment by ant0n-0x0000** [comment]
@Parking-Master That worked! Thankyou so much! Works flawlessly now.

**Comment by Parking-Master** [comment]
@ant0n-0x0000 you're welcome, and good to hear! Thanks for letting me know before the official push is made.

**Comment by Parking-Master** [comment]
@ant0n-0x0000 the official update has been pushed! Please try it again with `npm install node_characterai`. It should work like the forked version.
