### ISSUE TITLE
authenticateWithToken() hangs at the main character.ai website

### ISSUE THREAD

**Issue by ming736-2** [realcoloride/node_characterai#84]
When using authenticateWithToken(), it hangs at the main website, and never goes to the /auth0 endpoint.
![Screenshot_3081](https://github.com/realcoloride/node_characterai/assets/80364687/f04c96bb-d2a2-496a-9ba6-8b4638f6bfab)

I've tried #73 and Parking-Master's fork of node_characterai, all of which still seem to fail.

Edit: I've also tried clearing local storage manually, which still failed.

**Comment by Parking-Master** [comment]
Hello, all of these fixes will be implemented by tomorrow probably, so check in then! See #80 and #81.

**Comment by Parking-Master** [comment]
I see you've already tried the forked version. Have you tried opening in a non-headless version of puppeteer? Also what happens when you start your script, and watch the terminal?

**Comment by ming736-2** [comment]
> I see you've already tried the forked version. Have you tried opening in a non-headless version of puppeteer? Also what happens when you start your script, and watch the terminal?

I've opened a non-headless version, and yes, it stops at beta.character.ai, although the url at the top 
does change to the /auth0 endpoint, but the page never changes. Also, here's what happens when i start (i'm using a discord bot for this)
![Screenshot_3097](https://github.com/realcoloride/node_characterai/assets/80364687/0f28c440-870a-4da0-a3f1-0d94ddde08c8)

**Comment by Parking-Master** [comment]
Yep, luckily I the exact same thing is happening to me. I'll report it and keep you updated.

**Comment by realcoloride** [comment]
Is this chromium's fault?

**Comment by Parking-Master** [comment]
@realcoloride Looks like another bot blocker by cloudflare

**Comment by realcoloride** [comment]
> @realcoloride Looks like another bot blocker by cloudflare

Really?? What causes it this time, we just pushed a new update, I'll try the package again tomorrow

**Comment by Parking-Master** [comment]
@realcoloride I know, ironic, isn't it? It just worked right before you pushed the update. Sometimes I hate cloudflare.

**Comment by realcoloride** [comment]
Is it possible that you try (if that happens to you right now) deleting the node_modules folder and doing `npm i` again to clean and perhaps try to reinstall chromium and see what happens?

(Note: for windows, unless I'm wrong, the chromium executable gets directly installed when installing the `puppeteer` package)

**Comment by ming736-2** [comment]
> Is it possible that you try (if that happens to you right now) deleting the node_modules folder and doing `npm i` again to clean and perhaps try to reinstall chromium and see what happens?
> 
> (Note: for windows, unless I'm wrong, the chromium executable gets directly installed when installing the `puppeteer` package)

It still hangs.

**Comment by Parking-Master** [comment]
@realcoloride only on windows. For all other systems the binary file is only installed as a command. So wherever the path to the command to launch the browser is, that's the path.

**Comment by Parking-Master** [comment]
@ming736-2 did you try checking if chromium is installed with the above commands?

**Comment by realcoloride** [comment]
That's soooo weird, could you try checking the chrome's console to see for errors? (set the headless mode to false)

**Comment by Parking-Master** [comment]
Yeah,mif there's 403 or syntax errors in the console, you're definitely being blocked by cloudflare

**Comment by realcoloride** [comment]
Is a user agent issue perhaps?

**Comment by Parking-Master** [comment]
@realcoloride  maybe, even know I randomnized it a little more before you pushed it

**Comment by ming736-2** [comment]
> That's soooo weird, could you try checking the chrome's console to see for errors? (set the headless mode to false)

![image](https://github.com/realcoloride/node_characterai/assets/80364687/721e55da-af97-43ac-8a10-0fbaf500da1c)

**Comment by Parking-Master** [comment]
That's _not_ a bot blocking error

**Comment by Parking-Master** [comment]
Looks like an authentication error

**Comment by realcoloride** [comment]
Hello again, is the problem fixed for you?

**Comment by ming736-2** [comment]
> Hello again, is the problem fixed for you?

Sorry for the late reply, but the issue seems to be resolved.

**Comment by Parking-Master** [comment]
@ming736-2 good to hear! :D

**Comment by Parking-Master** [comment]
@realcoloride you can close this issue now.

**Comment by ming736-2** [comment]
Problems are rising again, unfortunately.

**Comment by realcoloride** [comment]
Hello, sorry to hear you have problems again.
Could you elaborate?

**Comment by ming736-2** [comment]
> Hello, sorry to hear you have problems again. Could you elaborate?

Same issue. It's hanging on the main character.ai website most of the time.

**Comment by Parking-Master** [comment]
Cloudflare issues 🙄

**Comment by Parking-Master** [comment]
Could you go to https://jwt.io, paste your auth token in the decoder and see if the output is valid? If it's a valid token, it will not give an error. Please do NOT comment the output, because it shows account information.

**Comment by ming736-2** [comment]
> Could you go to https://jwt.io, paste your auth token in the decoder and see if the output is valid? If it's a valid token, it will not give an error. Please do NOT comment the output, because it shows account information.

![image](https://github.com/realcoloride/node_characterai/assets/80364687/a22567e3-6432-4483-a07c-9fbbd788b50f)

**Comment by Parking-Master** [comment]
Hmm... that's strange. If you're getting a 401 unauthorized error, and your token is valid, I don't know what the problem could be.

In the mean time though, if you urgently need to use Character.AI in your project, you could try my new package https://github.com/Parking-Master/characterai

Follow the documentation to use it correctly. I'll keep you updated on this package still because we're still trying to figure out what the issue could be.

**Comment by realcoloride** [comment]
Hello again,

Could you say exactly at which part it hangs? Could you try to make console.log statements to check at where and when it does?
Also, another thing; Try setting the headless to `false`. When puppeteer isnt able to fully fetch whats needed it hangs until the response is "shown"

**Comment by Parking-Master** [comment]
@realcoloride in the original issue before it was closed/reopened, they set headless to `false` and screenshot the dev console, and it returned a 401 unauthorized status code, which doesn't usually show up in a working version. It's definitely got something to do with authoritizing, maybe the token

**Comment by realcoloride** [comment]
> @realcoloride in the original issue before it was closed/reopened, they set headless to `false` and screenshotted the dev console, and it returned a 401 unauthorized status code, which doesn't usually show up in a working version. It's definitely got something to do with authoritizing, maybe the token

I think the access key is wrong... They should try with another account and see

**Comment by realcoloride** [comment]
Can you use the character ai website regularly?

**Comment by ming736-2** [comment]
> Can you use the character ai website regularly?

Yes.

**Comment by realcoloride** [comment]
OP has not responded since, so I am closing this issue. If you still have problems, please feel free to re-open this issue or open a new one.
