### ISSUE TITLE
Ability to retrieve TTS?

### ISSUE THREAD

**Issue by sivertheisholt** [realcoloride/node_characterai#85]
Hello, thank you so much for this project! Helped me a ton in creating what I need. 

I'm looking for way to retrieve the TTS using the character voice. Is this possible in this project? As far as I understand the speech is returned if character voice is enabled. 

I do some manipulation on the string result from character AI before I forward it to some other applications. So I would like to generate the TTS from that instead.  

I see they have an endpoint for this: https://plus.character.ai/chat/character/preview-voice/?voice_id=22&to_speak=TextHere

I could simply use this directly I imagine, but It would be nice to have all in one place :)

**Comment by Parking-Master** [comment]
Hello, we'll consider adding this! Thanks for the feedback.

**Comment by realcoloride** [comment]
Looks like a good idea and I'll investigate on it. What does the endpoint return? I don't have CAI+.

**Comment by sivertheisholt** [comment]
> Looks like a good idea and I'll investigate on it. What does the endpoint return? I don't have CAI+.

It returns the following JSON:

`
{
  "speech": "base64 here"
}
`

**Comment by Parking-Master** [comment]
Perhaps if you got the base64 url, you could open a fake HTML page and play the audio with puppeteer? That "sounds" like a good idea, lol.

**Comment by sivertheisholt** [comment]
I forked the rep and managed to retrieve the base64 using the endpoint. Will open a PR later when I have time.

**Comment by Parking-Master** [comment]
@sivertheisholt good luck with it! I'll provide some example code that plays base64 audio using puppeteer. You could implement it and change some things to your requirements. Or you could just return the base64 string and not play the audio.

```javascript
const base64 = /* This is where the base64 audio will go */;
await page.evaluate(`let TTS = new Audio("${base64}"); TTS.play()`);
```

**Comment by sivertheisholt** [comment]
> @sivertheisholt good luck with it! I'll provide some example code that plays base64 audio using puppeteer. You could implement it and change some things to your requirements. Or you could just return the base64 string and not play the audio.
> 
> ```js
> const base64 = /* This is where the base64 audio will go */;
> await page.evaluate(`let TTS = new Audio("${base64}"); TTS.play()`);
> ```

Thank you! I will check it out :D

**Comment by Parking-Master** [comment]
@sivertheisholt nice! I also forgot to mention you need the entire base64 URI (data:audio/...;base64,...)

**Comment by realcoloride** [comment]
Ok that sounds cool!

However, if what we retrieve is the TTS object, what else? Is a method to convert it to a file is needed for example? Also, is it streamed or sent when done processing the message?

**Comment by Parking-Master** [comment]
@realcoloride
> However, if what we retrieve is the TTS object, what else? Is a method to convert it to a file is needed for example?

Nope, HTML can play a base64 audio file directly in the browser - no need to be converted to a file. Check the above example also

**Comment by realcoloride** [comment]
Closing issue, linked directly to PR #88
