### ISSUE TITLE
Discussion 

### ISSUE THREAD

**Issue by RichardDorian** [realcoloride/node_characterai#9]
This is not an issue, I just didn't find anywhere else to contact you.

This is sick! Finally someone who made a stable thing out of my idea. Where can I contact you (Discord maybe)? I wanna talk about a few things including the internals of this wrapper.

**Comment by RichardDorian** [comment]
Also I have a few ideas to improve by a lot this API wrapper 😀

**Comment by realcoloride** [comment]
Hello and pleasure to meet you Richard!

Sorry that you couldn't find nowhere to contact me.

My discord is **Coloride#8384**.

Looking forward!

Le sam. 25 févr. 2023 à 09:40, Richard Dorian ***@***.***> a
écrit :
