### ISSUE TITLE
Error: Request is already handled!

### ISSUE THREAD

**Issue by bazhenberg** [realcoloride/node_characterai#90]
Hello everyone. I'm working on a server and have used your library in it. The issue I'm facing is that with too frequent requests to the server (which, in turn, communicates with the Character.ai server), I encounter an error 'Error: Request is already handled!'.

The essence of the problem is that using my service where your library is involved will involve a lot of users. Does your library currently support a multi-user mode?

**Comment by bazhenberg** [comment]
/Users/gosudarevzakaz/Desktop/myproject/gd_character/node_modules/node_characterai/client.js:139
        if (request.status() === 200 || request.status() === 404) {
                    ^

TypeError: Cannot read properties of undefined (reading 'status')

**Comment by bazhenberg** [comment]
My idea is to have multiple users communicate with a bot through a single account. What is the best approach to achieve this? Should I use your library within my React application, or should I implement a server (Express.js) where your library handles responding to users?

**Comment by realcoloride** [comment]
Hello again and I am sorry I did not see this issue before.

Sadly, with how characterAI has been blocking bots and scrapping, it has became impossible to multitask it unless you have a beefy CPU thats able to run multiple chromium instances.

It used to be possible however before when it only required to use node-fetch. I am once again sorry. If there are ways to fix this issue more efficiently let me know.
