### ISSUE TITLE
Requests return 301 when using plus - Requests fail when using with NW.js/Electron

### ISSUE THREAD

**Issue by sivertheisholt** [realcoloride/node_characterai#91]
Hello,

When using plus it will redirect all requests to plus domain, so the first requests always returns 301. This works fine on its own, but when using this package with NW.js or Electron the 301 doesn't work. The request will just hang. I tried using a non plus account, and it all works fine because the request is never redirected. 

Fix for this would be to use the correct domain when set `usePlus` to true.

Im guessing when using it directly thru nodejs it will handle itself fine, but when you have electron/nwjs on top something happens.

**Comment by realcoloride** [comment]
usePlus is already replacing the sub domain (see requester.js)

**Comment by sivertheisholt** [comment]
Hmmm that is weird, I will check out more then. Cause that is not happening for me.

**Comment by sivertheisholt** [comment]
Do you have some kind of interceptor anywhere that replaces the hardcoded strings in client.js with plus domain?

**Comment by sivertheisholt** [comment]
I added this on the request function in requester.js and now the requests are not redirected and they work with NW.js:

` if(this.usePlus) url = url.replace("beta", "plus");`

**Comment by realcoloride** [comment]
Was the line remove? I swear there was something that used to check for the usePlus and add the subdomain

**Comment by sivertheisholt** [comment]
> Was the line remove? I swear there was something that used to check for the usePlus and add the subdomain

It does exist on the landing page, but not the requests:
`await page.goto("https://" + (this.usePlus ? "plus" : "beta") + ".character.ai");`

**Comment by realcoloride** [comment]
oh right, then do it for the requests please (using the same ? : operator)

**Comment by realcoloride** [comment]
Just before:

💡 I recommend that you frequently update this package for bug fixes and new additions.

Should be below the linux tips
"See [this](https://github.com/realcoloride/node_characterai/pull/89/files?short_path=b335630&unchanged=expanded#specifying-chromiums-path) for a fix."

& seems to be probematic

**Comment by Parking-Master** [comment]
Have any changes been made, or perhaps the issue has resolved on its own? If this is resolved, you can go ahead and close it

**Comment by sivertheisholt** [comment]
> Have any changes been made, or perhaps the issue has resolved on its own? If this is resolved, you can go ahead and close it

This is still a problem I believe if no changes have been made regarding the URL. I just haven't had the time to open a PR, it's just a one line fix.

**Comment by sivertheisholt** [comment]
Closing issue as it seems to be resolved.
