### ISSUE TITLE
What is the maximum allowable amount of bots I can upload at once?

### ISSUE THREAD

**Issue by bazhenberg** [realcoloride/node_characterai#94]
Hello! What is the maximum allowable amount of bots I can upload at once? I'm trying to upload 25 bots at once and I'm getting an error. If there are fewer of them, there are no problems

**Comment by realcoloride** [comment]
Hello,

What do you mean by "characters"?

**Comment by Parking-Master** [comment]
@realcoloride probably just a plain text message to the AI

**Comment by bazhenberg** [comment]
@realcoloride We're talking about characterAI.createOrContinueChat(id_characters). What is the limit on the number of times it can be used within one authenticateWithToken? In other words, how many characters can I initialize using authenticateWithToken in one go?

**Comment by bazhenberg** [comment]
error code: 1015 (cloudflare)

**Comment by Parking-Master** [comment]
@bazhenberg I'm pretty sure the API is only made to run 1 bot at once. You'll need to start several scripts probably to do that.

**Comment by realcoloride** [comment]
Before cloudflare it would be kind of unlimited, but with cloudflare/puppeteer it has been largely limited to 1 to 2

**Comment by realcoloride** [comment]
Hello, since this is inactive, I will close it

For extra information concerning automation, see https://github.com/realcoloride/node_characterai#troubleshooting in the **🪐 How to use an account to mass use the library?** part

Please re-open an issue if you have a problem.
