### ISSUE TITLE
Very slow

### ISSUE THREAD

**Issue by root-mega** [realcoloride/node_characterai#96]
Is it normal that it takes 4~ minutes to answer?

**Comment by realcoloride** [comment]
That is not normal. Could you provide more details on your issue?

**Comment by Parking-Master** [comment]
@realcoloride cloudflare recently made some changes to bot detection. Even my node_perplexityai API that I built broke. You may want to test it in a headful version of puppeteer

**Comment by realcoloride** [comment]
Oh no, not again

**Comment by Parking-Master** [comment]
Yep, clearly Character.AI doesn't want an API. It's bad business, they should just let it be

**Comment by Parking-Master** [comment]
This issue seems to be resolved, it takes about 15 seconds average for it to respond and about 20 seconds to set up. You can close this if you like

**Comment by realcoloride** [comment]
No news since, please re open this issue if you have any problems again
