### ISSUE TITLE
fetchCharacterInfo broken

### ISSUE THREAD

**Issue by Jeffgrey91** [realcoloride/node_characterai#97]
fetchCharacterInfo is not working. I checked the original code and the request is turning a http code 500 (internal server error).

```js
const request = await this.requester.request(`https://beta.character.ai/chat/character/info-cached/${characterId}/`, {
    headers: this.getHeaders(),
});

console.log(request.status()) // 500
```

**Comment by realcoloride** [comment]
I will investigate on this issue.

**Comment by Parking-Master** [comment]
@realcoloride just came to stop by for some help! 500 status code means internal server error. Character.AI must have changed their endpoint's API and things are probably different. Hope this helps!

**Comment by realcoloride** [comment]
Ok so upon investigation I discovered their endpoint was changed to something of /info
`https://beta.character.ai/chat/character/info/`
![image](https://github.com/realcoloride/node_characterai/assets/108619637/e39af253-6af9-4935-a12b-3df83cb0a5ea)

**Comment by Parking-Master** [comment]
@realcoloride great find! Does it work now?

**Comment by realcoloride** [comment]
> @realcoloride great find! Does it work now?

I haven't tested and found out how the request exactly works yet, but atleast the endpoint is there and i'll investigate on it
I will keep you updated

**Comment by realcoloride** [comment]
Update, I found out how it works, its via a json request, external_id being the key
![image](https://github.com/realcoloride/node_characterai/assets/108619637/97daefc1-413d-4ba9-b23a-1c212145592b)
![image](https://github.com/realcoloride/node_characterai/assets/108619637/4d662864-b76a-4b68-bea2-65ecc633996a)

**Comment by Parking-Master** [comment]
Yep, had a feeling that would be the issue

**Comment by realcoloride** [comment]
Hello again!
Sorry for the lack of information, I am pushing the update tonight when I come back home.

**Comment by realcoloride** [comment]
update, i fixed it:
![image](https://github.com/realcoloride/node_characterai/assets/108619637/b2f70c9b-6ebb-486b-b6ff-1d7884bc84b8)

I will push the commit and if it works for you I will push the update to the package

**Comment by Parking-Master** [comment]
@realcoloride nice! Guess the issue could be closed now.

**Comment by realcoloride** [comment]
Sorry parking master but I won't close this one until OP confirms it works
for them.

Did it work for you?

**Comment by realcoloride** [comment]
I have pushed update `1.2.1` to the node package.
+ node_characterai@1.2.1

If you have any problems let me know.

**Comment by Parking-Master** [comment]
@realcoloride that's okay!

**Comment by Parking-Master** [comment]
Oh yeah, and it does work fine. Just installed it and tested it

**Comment by Jeffgrey91** [comment]
@realcoloride Sorry for late response!
It's working now :) thank you!
